// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: clavel/project/v1/project.proto

package projectv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectSpecification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flakeref      string                 `protobuf:"bytes,1,opt,name=flakeref,proto3" json:"flakeref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectSpecification) Reset() {
	*x = ProjectSpecification{}
	mi := &file_clavel_project_v1_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectSpecification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectSpecification) ProtoMessage() {}

func (x *ProjectSpecification) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_project_v1_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectSpecification.ProtoReflect.Descriptor instead.
func (*ProjectSpecification) Descriptor() ([]byte, []int) {
	return file_clavel_project_v1_project_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectSpecification) GetFlakeref() string {
	if x != nil {
		return x.Flakeref
	}
	return ""
}

type ProjectServiceShowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceShowRequest) Reset() {
	*x = ProjectServiceShowRequest{}
	mi := &file_clavel_project_v1_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceShowRequest) ProtoMessage() {}

func (x *ProjectServiceShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_project_v1_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceShowRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceShowRequest) Descriptor() ([]byte, []int) {
	return file_clavel_project_v1_project_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectServiceShowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProjectServiceShowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Spec          *ProjectSpecification  `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceShowResponse) Reset() {
	*x = ProjectServiceShowResponse{}
	mi := &file_clavel_project_v1_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceShowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceShowResponse) ProtoMessage() {}

func (x *ProjectServiceShowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_project_v1_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceShowResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceShowResponse) Descriptor() ([]byte, []int) {
	return file_clavel_project_v1_project_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectServiceShowResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectServiceShowResponse) GetSpec() *ProjectSpecification {
	if x != nil {
		return x.Spec
	}
	return nil
}

type ProjectServiceAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Spec          *ProjectSpecification  `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceAddRequest) Reset() {
	*x = ProjectServiceAddRequest{}
	mi := &file_clavel_project_v1_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceAddRequest) ProtoMessage() {}

func (x *ProjectServiceAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_project_v1_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceAddRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceAddRequest) Descriptor() ([]byte, []int) {
	return file_clavel_project_v1_project_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectServiceAddRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectServiceAddRequest) GetSpec() *ProjectSpecification {
	if x != nil {
		return x.Spec
	}
	return nil
}

type ProjectServiceAddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceAddResponse) Reset() {
	*x = ProjectServiceAddResponse{}
	mi := &file_clavel_project_v1_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceAddResponse) ProtoMessage() {}

func (x *ProjectServiceAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_project_v1_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceAddResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceAddResponse) Descriptor() ([]byte, []int) {
	return file_clavel_project_v1_project_proto_rawDescGZIP(), []int{4}
}

var File_clavel_project_v1_project_proto protoreflect.FileDescriptor

const file_clavel_project_v1_project_proto_rawDesc = "" +
	"\n" +
	"\x1fclavel/project/v1/project.proto\x12\x11clavel.project.v1\"2\n" +
	"\x14ProjectSpecification\x12\x1a\n" +
	"\bflakeref\x18\x01 \x01(\tR\bflakeref\"/\n" +
	"\x19ProjectServiceShowRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"m\n" +
	"\x1aProjectServiceShowResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\x04spec\x18\x02 \x01(\v2'.clavel.project.v1.ProjectSpecificationR\x04spec\"k\n" +
	"\x18ProjectServiceAddRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\x04spec\x18\x02 \x01(\v2'.clavel.project.v1.ProjectSpecificationR\x04spec\"\x1b\n" +
	"\x19ProjectServiceAddResponse2\xdb\x01\n" +
	"\x0eProjectService\x12e\n" +
	"\x04Show\x12,.clavel.project.v1.ProjectServiceShowRequest\x1a-.clavel.project.v1.ProjectServiceShowResponse\"\x00\x12b\n" +
	"\x03Add\x12+.clavel.project.v1.ProjectServiceAddRequest\x1a,.clavel.project.v1.ProjectServiceAddResponse\"\x00B7Z5github.com/erikeah/clavel/pkg/pb/project/v1;projectv1b\x06proto3"

var (
	file_clavel_project_v1_project_proto_rawDescOnce sync.Once
	file_clavel_project_v1_project_proto_rawDescData []byte
)

func file_clavel_project_v1_project_proto_rawDescGZIP() []byte {
	file_clavel_project_v1_project_proto_rawDescOnce.Do(func() {
		file_clavel_project_v1_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clavel_project_v1_project_proto_rawDesc), len(file_clavel_project_v1_project_proto_rawDesc)))
	})
	return file_clavel_project_v1_project_proto_rawDescData
}

var file_clavel_project_v1_project_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_clavel_project_v1_project_proto_goTypes = []any{
	(*ProjectSpecification)(nil),       // 0: clavel.project.v1.ProjectSpecification
	(*ProjectServiceShowRequest)(nil),  // 1: clavel.project.v1.ProjectServiceShowRequest
	(*ProjectServiceShowResponse)(nil), // 2: clavel.project.v1.ProjectServiceShowResponse
	(*ProjectServiceAddRequest)(nil),   // 3: clavel.project.v1.ProjectServiceAddRequest
	(*ProjectServiceAddResponse)(nil),  // 4: clavel.project.v1.ProjectServiceAddResponse
}
var file_clavel_project_v1_project_proto_depIdxs = []int32{
	0, // 0: clavel.project.v1.ProjectServiceShowResponse.spec:type_name -> clavel.project.v1.ProjectSpecification
	0, // 1: clavel.project.v1.ProjectServiceAddRequest.spec:type_name -> clavel.project.v1.ProjectSpecification
	1, // 2: clavel.project.v1.ProjectService.Show:input_type -> clavel.project.v1.ProjectServiceShowRequest
	3, // 3: clavel.project.v1.ProjectService.Add:input_type -> clavel.project.v1.ProjectServiceAddRequest
	2, // 4: clavel.project.v1.ProjectService.Show:output_type -> clavel.project.v1.ProjectServiceShowResponse
	4, // 5: clavel.project.v1.ProjectService.Add:output_type -> clavel.project.v1.ProjectServiceAddResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_clavel_project_v1_project_proto_init() }
func file_clavel_project_v1_project_proto_init() {
	if File_clavel_project_v1_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clavel_project_v1_project_proto_rawDesc), len(file_clavel_project_v1_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clavel_project_v1_project_proto_goTypes,
		DependencyIndexes: file_clavel_project_v1_project_proto_depIdxs,
		MessageInfos:      file_clavel_project_v1_project_proto_msgTypes,
	}.Build()
	File_clavel_project_v1_project_proto = out.File
	file_clavel_project_v1_project_proto_goTypes = nil
	file_clavel_project_v1_project_proto_depIdxs = nil
}
