// Package clavelgen renders Nix descriptor files from proto messages and
// drives clavel-gen either as a buf/protoc plugin or a standalone emitter.
package clavelgen

import (
	"encoding/base64"
	"fmt"
	"strings"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
)

func lowerCamel(name string) string {
	if name == "" {
		return name
	}
	return strings.ToLower(name[:1]) + name[1:]
}

// collectMessages returns the messages reachable from nested fields of md,
// keyed by lowerCamel name.
func collectMessages(md protoreflect.MessageDescriptor, out map[string]protoreflect.MessageDescriptor) {
	for i := 0; i < md.Fields().Len(); i++ {
		fd := md.Fields().Get(i)
		if fd.Kind() != protoreflect.MessageKind && fd.Kind() != protoreflect.GroupKind {
			continue
		}
		nested := fd.Message()
		if _, ok := out[lowerCamel(string(nested.Name()))]; ok {
			continue
		}
		out[lowerCamel(string(nested.Name()))] = nested
		collectMessages(nested, out)
	}
}

func nixType(fd protoreflect.FieldDescriptor) string {
	base := func(k protoreflect.Kind) string {
		switch k {
		case protoreflect.StringKind, protoreflect.BytesKind, protoreflect.EnumKind:
			return "types.str"
		case protoreflect.BoolKind:
			return "types.bool"
		case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Uint32Kind,
			protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Uint64Kind,
			protoreflect.Fixed32Kind, protoreflect.Sfixed32Kind, protoreflect.Fixed64Kind,
			protoreflect.Sfixed64Kind:
			return "types.int"
		case protoreflect.FloatKind, protoreflect.DoubleKind:
			return "types.float"
		case protoreflect.MessageKind, protoreflect.GroupKind:
			return lowerCamel(string(fd.Message().Name()))
		default:
			return "types.anything"
		}
	}
	if fd.IsMap() {
		return fmt.Sprintf("(types.attrsOf %s)", nixType(fd.MapValue()))
	}
	if fd.IsList() {
		return fmt.Sprintf("(types.listOf %s)", base(fd.Kind()))
	}
	return base(fd.Kind())
}

func defaultFor(fd protoreflect.FieldDescriptor) (string, bool) {
	if fd.IsMap() {
		return "{ }", true
	}
	if fd.IsList() {
		return "[ ]", true
	}
	return "", false
}

func renderOptions(md protoreflect.MessageDescriptor, sb *strings.Builder, indent string) {
	sb.WriteString(indent + "options = {\n")
	for i := 0; i < md.Fields().Len(); i++ {
		fd := md.Fields().Get(i)
		name := string(fd.Name())
		sb.WriteString(indent + "  " + name + " = mkOption {\n")
		sb.WriteString(indent + "    type = " + nixType(fd) + ";\n")
		if def, ok := defaultFor(fd); ok {
			sb.WriteString(indent + "    default = " + def + ";\n")
		}
		sb.WriteString(indent + "  };\n")
	}
	sb.WriteString(indent + "};\n")
}

// Generate renders the Nix descriptor + spec type for the given spec message.
// schema is the base64-encoded FileDescriptorSet to embed.
func Generate(group, version, kind, plural, specMessage, schema string, specMD protoreflect.MessageDescriptor) string {
	nested := map[string]protoreflect.MessageDescriptor{}
	collectMessages(specMD, nested)

	var sb strings.Builder
	sb.WriteString("# Generated by clavel-gen. DO NOT EDIT.\n")
	sb.WriteString("{ lib }:\n")
	sb.WriteString("let\n")
	sb.WriteString("  inherit (lib) mkOption types;\n")
	for name, md := range nested {
		sb.WriteString("  " + name + " = types.submodule {\n")
		renderOptions(md, &sb, "    ")
		sb.WriteString("  };\n")
	}
	sb.WriteString("in\n")
	sb.WriteString("{\n")
	sb.WriteString("  descriptor = {\n")
	sb.WriteString(fmt.Sprintf("    group = %q;\n", group))
	sb.WriteString(fmt.Sprintf("    version = %q;\n", version))
	sb.WriteString(fmt.Sprintf("    kind = %q;\n", kind))
	sb.WriteString(fmt.Sprintf("    plural = %q;\n", plural))
	sb.WriteString(fmt.Sprintf("    specMessage = %q;\n", specMessage))
	sb.WriteString(fmt.Sprintf("    schema = %q;\n", schema))
	sb.WriteString("  };\n")
	sb.WriteString("\n")
	sb.WriteString("  spec = types.submodule {\n")
	renderOptions(specMD, &sb, "    ")
	sb.WriteString("  };\n")
	sb.WriteString("}\n")
	return sb.String()
}

// EncodeDescriptorSet serializes the given file descriptors and returns their
// base64 encoding for use as a CRD schema.
func EncodeDescriptorSet(files []*descriptorpb.FileDescriptorProto) (string, error) {
	b, err := proto.Marshal(&descriptorpb.FileDescriptorSet{File: files})
	if err != nil {
		return "", err
	}
	return base64.StdEncoding.EncodeToString(b), nil
}

// FindMessage returns the message with the given fully-qualified name within
// md's tree of nested messages.
func FindMessage(md protoreflect.MessageDescriptor, full protoreflect.FullName) protoreflect.MessageDescriptor {
	if md.FullName() == full {
		return md
	}
	for i := 0; i < md.Messages().Len(); i++ {
		if m := FindMessage(md.Messages().Get(i), full); m != nil {
			return m
		}
	}
	return nil
}
