// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: clavel/core/v1/artifact.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtifactStatusPhase int32

const (
	ArtifactStatusPhase_ARTIFACT_STATUS_PHASE_UNSPECIFIED ArtifactStatusPhase = 0
	ArtifactStatusPhase_ARTIFACT_STATUS_PHASE_PENDING     ArtifactStatusPhase = 1
	ArtifactStatusPhase_ARTIFACT_STATUS_PHASE_SUCCEEDED   ArtifactStatusPhase = 2
	ArtifactStatusPhase_ARTIFACT_STATUS_PHASE_FAILED      ArtifactStatusPhase = 3
)

// Enum value maps for ArtifactStatusPhase.
var (
	ArtifactStatusPhase_name = map[int32]string{
		0: "ARTIFACT_STATUS_PHASE_UNSPECIFIED",
		1: "ARTIFACT_STATUS_PHASE_PENDING",
		2: "ARTIFACT_STATUS_PHASE_SUCCEEDED",
		3: "ARTIFACT_STATUS_PHASE_FAILED",
	}
	ArtifactStatusPhase_value = map[string]int32{
		"ARTIFACT_STATUS_PHASE_UNSPECIFIED": 0,
		"ARTIFACT_STATUS_PHASE_PENDING":     1,
		"ARTIFACT_STATUS_PHASE_SUCCEEDED":   2,
		"ARTIFACT_STATUS_PHASE_FAILED":      3,
	}
)

func (x ArtifactStatusPhase) Enum() *ArtifactStatusPhase {
	p := new(ArtifactStatusPhase)
	*p = x
	return p
}

func (x ArtifactStatusPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArtifactStatusPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_clavel_core_v1_artifact_proto_enumTypes[0].Descriptor()
}

func (ArtifactStatusPhase) Type() protoreflect.EnumType {
	return &file_clavel_core_v1_artifact_proto_enumTypes[0]
}

func (x ArtifactStatusPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArtifactStatusPhase.Descriptor instead.
func (ArtifactStatusPhase) EnumDescriptor() ([]byte, []int) {
	return file_clavel_core_v1_artifact_proto_rawDescGZIP(), []int{0}
}

// ArtifactStorePath names the Evaluation whose result names the store path
// this artifact points at. The dependency is the evalRef: a consumer needs the
// result of an Evaluation, never that Evaluation's expression.
type ArtifactStorePath struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the Evaluation owning the store path.
	EvalRef       string `protobuf:"bytes,1,opt,name=eval_ref,json=evalRef,proto3" json:"eval_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactStorePath) Reset() {
	*x = ArtifactStorePath{}
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactStorePath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactStorePath) ProtoMessage() {}

func (x *ArtifactStorePath) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactStorePath.ProtoReflect.Descriptor instead.
func (*ArtifactStorePath) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_artifact_proto_rawDescGZIP(), []int{0}
}

func (x *ArtifactStorePath) GetEvalRef() string {
	if x != nil {
		return x.EvalRef
	}
	return ""
}

type ArtifactSpecification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Store the path is looked up in, e.g. https://cache.nixos.org. Empty means
	// the local store.
	Store         string             `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	StorePath     *ArtifactStorePath `protobuf:"bytes,2,opt,name=store_path,json=storePath,proto3" json:"store_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactSpecification) Reset() {
	*x = ArtifactSpecification{}
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactSpecification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactSpecification) ProtoMessage() {}

func (x *ArtifactSpecification) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactSpecification.ProtoReflect.Descriptor instead.
func (*ArtifactSpecification) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_artifact_proto_rawDescGZIP(), []int{1}
}

func (x *ArtifactSpecification) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *ArtifactSpecification) GetStorePath() *ArtifactStorePath {
	if x != nil {
		return x.StorePath
	}
	return nil
}

type ArtifactStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Phase ArtifactStatusPhase    `protobuf:"varint,1,opt,name=phase,proto3,enum=clavel.core.v1.ArtifactStatusPhase" json:"phase,omitempty"`
	// Store path the evalRef resolved to. Recorded while the path is confirmed
	// present so a consumer reads the resolved reference directly, even after
	// the spec has changed.
	StorePath          string `protobuf:"bytes,2,opt,name=store_path,json=storePath,proto3" json:"store_path,omitempty"`
	ObservedGeneration int64  `protobuf:"varint,3,opt,name=observed_generation,json=observedGeneration,proto3" json:"observed_generation,omitempty"`
	Message            string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ArtifactStatus) Reset() {
	*x = ArtifactStatus{}
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactStatus) ProtoMessage() {}

func (x *ArtifactStatus) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactStatus.ProtoReflect.Descriptor instead.
func (*ArtifactStatus) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_artifact_proto_rawDescGZIP(), []int{2}
}

func (x *ArtifactStatus) GetPhase() ArtifactStatusPhase {
	if x != nil {
		return x.Phase
	}
	return ArtifactStatusPhase_ARTIFACT_STATUS_PHASE_UNSPECIFIED
}

func (x *ArtifactStatus) GetStorePath() string {
	if x != nil {
		return x.StorePath
	}
	return ""
}

func (x *ArtifactStatus) GetObservedGeneration() int64 {
	if x != nil {
		return x.ObservedGeneration
	}
	return 0
}

func (x *ArtifactStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Status        *ArtifactStatus        `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Spec          *ArtifactSpecification `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	ApiVersion    string                 `protobuf:"bytes,4,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind          string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_artifact_proto_rawDescGZIP(), []int{3}
}

func (x *Artifact) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Artifact) GetStatus() *ArtifactStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Artifact) GetSpec() *ArtifactSpecification {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Artifact) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Artifact) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type ArtifactServiceShowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactServiceShowRequest) Reset() {
	*x = ArtifactServiceShowRequest{}
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactServiceShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactServiceShowRequest) ProtoMessage() {}

func (x *ArtifactServiceShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactServiceShowRequest.ProtoReflect.Descriptor instead.
func (*ArtifactServiceShowRequest) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_artifact_proto_rawDescGZIP(), []int{4}
}

func (x *ArtifactServiceShowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ArtifactServiceShowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Artifact              `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactServiceShowResponse) Reset() {
	*x = ArtifactServiceShowResponse{}
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactServiceShowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactServiceShowResponse) ProtoMessage() {}

func (x *ArtifactServiceShowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactServiceShowResponse.ProtoReflect.Descriptor instead.
func (*ArtifactServiceShowResponse) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_artifact_proto_rawDescGZIP(), []int{5}
}

func (x *ArtifactServiceShowResponse) GetData() *Artifact {
	if x != nil {
		return x.Data
	}
	return nil
}

type ArtifactServiceCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Artifact              `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactServiceCreateRequest) Reset() {
	*x = ArtifactServiceCreateRequest{}
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactServiceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactServiceCreateRequest) ProtoMessage() {}

func (x *ArtifactServiceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactServiceCreateRequest.ProtoReflect.Descriptor instead.
func (*ArtifactServiceCreateRequest) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_artifact_proto_rawDescGZIP(), []int{6}
}

func (x *ArtifactServiceCreateRequest) GetData() *Artifact {
	if x != nil {
		return x.Data
	}
	return nil
}

type ArtifactServiceCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactServiceCreateResponse) Reset() {
	*x = ArtifactServiceCreateResponse{}
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactServiceCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactServiceCreateResponse) ProtoMessage() {}

func (x *ArtifactServiceCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactServiceCreateResponse.ProtoReflect.Descriptor instead.
func (*ArtifactServiceCreateResponse) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_artifact_proto_rawDescGZIP(), []int{7}
}

type ArtifactServiceListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactServiceListRequest) Reset() {
	*x = ArtifactServiceListRequest{}
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactServiceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactServiceListRequest) ProtoMessage() {}

func (x *ArtifactServiceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactServiceListRequest.ProtoReflect.Descriptor instead.
func (*ArtifactServiceListRequest) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_artifact_proto_rawDescGZIP(), []int{8}
}

type ArtifactServiceListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Artifact            `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactServiceListResponse) Reset() {
	*x = ArtifactServiceListResponse{}
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactServiceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactServiceListResponse) ProtoMessage() {}

func (x *ArtifactServiceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactServiceListResponse.ProtoReflect.Descriptor instead.
func (*ArtifactServiceListResponse) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_artifact_proto_rawDescGZIP(), []int{9}
}

func (x *ArtifactServiceListResponse) GetData() []*Artifact {
	if x != nil {
		return x.Data
	}
	return nil
}

type ArtifactServiceDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactServiceDeleteRequest) Reset() {
	*x = ArtifactServiceDeleteRequest{}
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactServiceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactServiceDeleteRequest) ProtoMessage() {}

func (x *ArtifactServiceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactServiceDeleteRequest.ProtoReflect.Descriptor instead.
func (*ArtifactServiceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_artifact_proto_rawDescGZIP(), []int{10}
}

func (x *ArtifactServiceDeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ArtifactServiceDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactServiceDeleteResponse) Reset() {
	*x = ArtifactServiceDeleteResponse{}
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactServiceDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactServiceDeleteResponse) ProtoMessage() {}

func (x *ArtifactServiceDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactServiceDeleteResponse.ProtoReflect.Descriptor instead.
func (*ArtifactServiceDeleteResponse) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_artifact_proto_rawDescGZIP(), []int{11}
}

type ArtifactServiceUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data          *Artifact              `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactServiceUpdateRequest) Reset() {
	*x = ArtifactServiceUpdateRequest{}
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactServiceUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactServiceUpdateRequest) ProtoMessage() {}

func (x *ArtifactServiceUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactServiceUpdateRequest.ProtoReflect.Descriptor instead.
func (*ArtifactServiceUpdateRequest) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_artifact_proto_rawDescGZIP(), []int{12}
}

func (x *ArtifactServiceUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArtifactServiceUpdateRequest) GetData() *Artifact {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ArtifactServiceUpdateRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type ArtifactServiceUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactServiceUpdateResponse) Reset() {
	*x = ArtifactServiceUpdateResponse{}
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactServiceUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactServiceUpdateResponse) ProtoMessage() {}

func (x *ArtifactServiceUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactServiceUpdateResponse.ProtoReflect.Descriptor instead.
func (*ArtifactServiceUpdateResponse) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_artifact_proto_rawDescGZIP(), []int{13}
}

type ArtifactServiceWatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ask the server to stream the current state first, terminated by an
	// EVENT_TYPE_SYNC marker, before forwarding changes.
	List          bool `protobuf:"varint,1,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactServiceWatchRequest) Reset() {
	*x = ArtifactServiceWatchRequest{}
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactServiceWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactServiceWatchRequest) ProtoMessage() {}

func (x *ArtifactServiceWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactServiceWatchRequest.ProtoReflect.Descriptor instead.
func (*ArtifactServiceWatchRequest) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_artifact_proto_rawDescGZIP(), []int{14}
}

func (x *ArtifactServiceWatchRequest) GetList() bool {
	if x != nil {
		return x.List
	}
	return false
}

type ArtifactServiceWatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Data  *Artifact              `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// What happened. EVENT_TYPE_PUT carries data; EVENT_TYPE_DELETE carries only
	// name; EVENT_TYPE_SYNC carries neither.
	Type EventType `protobuf:"varint,3,opt,name=type,proto3,enum=clavel.core.v1.EventType" json:"type,omitempty"`
	// Identity of the resource the event refers to, set on every event.
	Name          string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactServiceWatchResponse) Reset() {
	*x = ArtifactServiceWatchResponse{}
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactServiceWatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactServiceWatchResponse) ProtoMessage() {}

func (x *ArtifactServiceWatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_artifact_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactServiceWatchResponse.ProtoReflect.Descriptor instead.
func (*ArtifactServiceWatchResponse) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_artifact_proto_rawDescGZIP(), []int{15}
}

func (x *ArtifactServiceWatchResponse) GetData() *Artifact {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ArtifactServiceWatchResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ArtifactServiceWatchResponse) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *ArtifactServiceWatchResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_clavel_core_v1_artifact_proto protoreflect.FileDescriptor

const file_clavel_core_v1_artifact_proto_rawDesc = "" +
	"\n" +
	"\x1dclavel/core/v1/artifact.proto\x12\x0eclavel.core.v1\x1a\x1aclavel/core/v1/event.proto\x1a\x1fclavel/core/v1/evaluation.proto\x1a\x1dclavel/core/v1/metadata.proto\x1a google/protobuf/field_mask.proto\".\n" +
	"\x11ArtifactStorePath\x12\x19\n" +
	"\beval_ref\x18\x01 \x01(\tR\aevalRef\"o\n" +
	"\x15ArtifactSpecification\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12@\n" +
	"\n" +
	"store_path\x18\x02 \x01(\v2!.clavel.core.v1.ArtifactStorePathR\tstorePath\"\xb5\x01\n" +
	"\x0eArtifactStatus\x129\n" +
	"\x05phase\x18\x01 \x01(\x0e2#.clavel.core.v1.ArtifactStatusPhaseR\x05phase\x12\x1d\n" +
	"\n" +
	"store_path\x18\x02 \x01(\tR\tstorePath\x12/\n" +
	"\x13observed_generation\x18\x03 \x01(\x03R\x12observedGeneration\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xe8\x01\n" +
	"\bArtifact\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.clavel.core.v1.MetadataR\bmetadata\x126\n" +
	"\x06status\x18\x02 \x01(\v2\x1e.clavel.core.v1.ArtifactStatusR\x06status\x129\n" +
	"\x04spec\x18\x03 \x01(\v2%.clavel.core.v1.ArtifactSpecificationR\x04spec\x12\x1f\n" +
	"\vapi_version\x18\x04 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\"0\n" +
	"\x1aArtifactServiceShowRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"K\n" +
	"\x1bArtifactServiceShowResponse\x12,\n" +
	"\x04data\x18\x01 \x01(\v2\x18.clavel.core.v1.ArtifactR\x04data\"L\n" +
	"\x1cArtifactServiceCreateRequest\x12,\n" +
	"\x04data\x18\x01 \x01(\v2\x18.clavel.core.v1.ArtifactR\x04data\"\x1f\n" +
	"\x1dArtifactServiceCreateResponse\"\x1c\n" +
	"\x1aArtifactServiceListRequest\"K\n" +
	"\x1bArtifactServiceListResponse\x12,\n" +
	"\x04data\x18\x01 \x03(\v2\x18.clavel.core.v1.ArtifactR\x04data\"2\n" +
	"\x1cArtifactServiceDeleteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1f\n" +
	"\x1dArtifactServiceDeleteResponse\"\x9d\x01\n" +
	"\x1cArtifactServiceUpdateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x04data\x18\x02 \x01(\v2\x18.clavel.core.v1.ArtifactR\x04data\x12;\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\x1f\n" +
	"\x1dArtifactServiceUpdateResponse\"1\n" +
	"\x1bArtifactServiceWatchRequest\x12\x12\n" +
	"\x04list\x18\x01 \x01(\bR\x04list\"\xbc\x01\n" +
	"\x1cArtifactServiceWatchResponse\x12,\n" +
	"\x04data\x18\x01 \x01(\v2\x18.clavel.core.v1.ArtifactR\x04data\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x15.clavel.core.v1.ErrorR\x05error\x12-\n" +
	"\x04type\x18\x03 \x01(\x0e2\x19.clavel.core.v1.EventTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name*\xa6\x01\n" +
	"\x13ArtifactStatusPhase\x12%\n" +
	"!ARTIFACT_STATUS_PHASE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dARTIFACT_STATUS_PHASE_PENDING\x10\x01\x12#\n" +
	"\x1fARTIFACT_STATUS_PHASE_SUCCEEDED\x10\x02\x12 \n" +
	"\x1cARTIFACT_STATUS_PHASE_FAILED\x10\x032\xfa\x04\n" +
	"\x0fArtifactService\x12a\n" +
	"\x04Show\x12*.clavel.core.v1.ArtifactServiceShowRequest\x1a+.clavel.core.v1.ArtifactServiceShowResponse\"\x00\x12a\n" +
	"\x04List\x12*.clavel.core.v1.ArtifactServiceListRequest\x1a+.clavel.core.v1.ArtifactServiceListResponse\"\x00\x12g\n" +
	"\x06Create\x12,.clavel.core.v1.ArtifactServiceCreateRequest\x1a-.clavel.core.v1.ArtifactServiceCreateResponse\"\x00\x12g\n" +
	"\x06Update\x12,.clavel.core.v1.ArtifactServiceUpdateRequest\x1a-.clavel.core.v1.ArtifactServiceUpdateResponse\"\x00\x12g\n" +
	"\x06Delete\x12,.clavel.core.v1.ArtifactServiceDeleteRequest\x1a-.clavel.core.v1.ArtifactServiceDeleteResponse\"\x00\x12f\n" +
	"\x05Watch\x12+.clavel.core.v1.ArtifactServiceWatchRequest\x1a,.clavel.core.v1.ArtifactServiceWatchResponse\"\x000\x01B2Z0github.com/erikeah/clavel/pkg/api/core/v1;corev1b\x06proto3"

var (
	file_clavel_core_v1_artifact_proto_rawDescOnce sync.Once
	file_clavel_core_v1_artifact_proto_rawDescData []byte
)

func file_clavel_core_v1_artifact_proto_rawDescGZIP() []byte {
	file_clavel_core_v1_artifact_proto_rawDescOnce.Do(func() {
		file_clavel_core_v1_artifact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clavel_core_v1_artifact_proto_rawDesc), len(file_clavel_core_v1_artifact_proto_rawDesc)))
	})
	return file_clavel_core_v1_artifact_proto_rawDescData
}

var file_clavel_core_v1_artifact_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_clavel_core_v1_artifact_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_clavel_core_v1_artifact_proto_goTypes = []any{
	(ArtifactStatusPhase)(0),              // 0: clavel.core.v1.ArtifactStatusPhase
	(*ArtifactStorePath)(nil),             // 1: clavel.core.v1.ArtifactStorePath
	(*ArtifactSpecification)(nil),         // 2: clavel.core.v1.ArtifactSpecification
	(*ArtifactStatus)(nil),                // 3: clavel.core.v1.ArtifactStatus
	(*Artifact)(nil),                      // 4: clavel.core.v1.Artifact
	(*ArtifactServiceShowRequest)(nil),    // 5: clavel.core.v1.ArtifactServiceShowRequest
	(*ArtifactServiceShowResponse)(nil),   // 6: clavel.core.v1.ArtifactServiceShowResponse
	(*ArtifactServiceCreateRequest)(nil),  // 7: clavel.core.v1.ArtifactServiceCreateRequest
	(*ArtifactServiceCreateResponse)(nil), // 8: clavel.core.v1.ArtifactServiceCreateResponse
	(*ArtifactServiceListRequest)(nil),    // 9: clavel.core.v1.ArtifactServiceListRequest
	(*ArtifactServiceListResponse)(nil),   // 10: clavel.core.v1.ArtifactServiceListResponse
	(*ArtifactServiceDeleteRequest)(nil),  // 11: clavel.core.v1.ArtifactServiceDeleteRequest
	(*ArtifactServiceDeleteResponse)(nil), // 12: clavel.core.v1.ArtifactServiceDeleteResponse
	(*ArtifactServiceUpdateRequest)(nil),  // 13: clavel.core.v1.ArtifactServiceUpdateRequest
	(*ArtifactServiceUpdateResponse)(nil), // 14: clavel.core.v1.ArtifactServiceUpdateResponse
	(*ArtifactServiceWatchRequest)(nil),   // 15: clavel.core.v1.ArtifactServiceWatchRequest
	(*ArtifactServiceWatchResponse)(nil),  // 16: clavel.core.v1.ArtifactServiceWatchResponse
	(*Metadata)(nil),                      // 17: clavel.core.v1.Metadata
	(*fieldmaskpb.FieldMask)(nil),         // 18: google.protobuf.FieldMask
	(*Error)(nil),                         // 19: clavel.core.v1.Error
	(EventType)(0),                        // 20: clavel.core.v1.EventType
}
var file_clavel_core_v1_artifact_proto_depIdxs = []int32{
	1,  // 0: clavel.core.v1.ArtifactSpecification.store_path:type_name -> clavel.core.v1.ArtifactStorePath
	0,  // 1: clavel.core.v1.ArtifactStatus.phase:type_name -> clavel.core.v1.ArtifactStatusPhase
	17, // 2: clavel.core.v1.Artifact.metadata:type_name -> clavel.core.v1.Metadata
	3,  // 3: clavel.core.v1.Artifact.status:type_name -> clavel.core.v1.ArtifactStatus
	2,  // 4: clavel.core.v1.Artifact.spec:type_name -> clavel.core.v1.ArtifactSpecification
	4,  // 5: clavel.core.v1.ArtifactServiceShowResponse.data:type_name -> clavel.core.v1.Artifact
	4,  // 6: clavel.core.v1.ArtifactServiceCreateRequest.data:type_name -> clavel.core.v1.Artifact
	4,  // 7: clavel.core.v1.ArtifactServiceListResponse.data:type_name -> clavel.core.v1.Artifact
	4,  // 8: clavel.core.v1.ArtifactServiceUpdateRequest.data:type_name -> clavel.core.v1.Artifact
	18, // 9: clavel.core.v1.ArtifactServiceUpdateRequest.update_mask:type_name -> google.protobuf.FieldMask
	4,  // 10: clavel.core.v1.ArtifactServiceWatchResponse.data:type_name -> clavel.core.v1.Artifact
	19, // 11: clavel.core.v1.ArtifactServiceWatchResponse.error:type_name -> clavel.core.v1.Error
	20, // 12: clavel.core.v1.ArtifactServiceWatchResponse.type:type_name -> clavel.core.v1.EventType
	5,  // 13: clavel.core.v1.ArtifactService.Show:input_type -> clavel.core.v1.ArtifactServiceShowRequest
	9,  // 14: clavel.core.v1.ArtifactService.List:input_type -> clavel.core.v1.ArtifactServiceListRequest
	7,  // 15: clavel.core.v1.ArtifactService.Create:input_type -> clavel.core.v1.ArtifactServiceCreateRequest
	13, // 16: clavel.core.v1.ArtifactService.Update:input_type -> clavel.core.v1.ArtifactServiceUpdateRequest
	11, // 17: clavel.core.v1.ArtifactService.Delete:input_type -> clavel.core.v1.ArtifactServiceDeleteRequest
	15, // 18: clavel.core.v1.ArtifactService.Watch:input_type -> clavel.core.v1.ArtifactServiceWatchRequest
	6,  // 19: clavel.core.v1.ArtifactService.Show:output_type -> clavel.core.v1.ArtifactServiceShowResponse
	10, // 20: clavel.core.v1.ArtifactService.List:output_type -> clavel.core.v1.ArtifactServiceListResponse
	8,  // 21: clavel.core.v1.ArtifactService.Create:output_type -> clavel.core.v1.ArtifactServiceCreateResponse
	14, // 22: clavel.core.v1.ArtifactService.Update:output_type -> clavel.core.v1.ArtifactServiceUpdateResponse
	12, // 23: clavel.core.v1.ArtifactService.Delete:output_type -> clavel.core.v1.ArtifactServiceDeleteResponse
	16, // 24: clavel.core.v1.ArtifactService.Watch:output_type -> clavel.core.v1.ArtifactServiceWatchResponse
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_clavel_core_v1_artifact_proto_init() }
func file_clavel_core_v1_artifact_proto_init() {
	if File_clavel_core_v1_artifact_proto != nil {
		return
	}
	file_clavel_core_v1_event_proto_init()
	file_clavel_core_v1_evaluation_proto_init()
	file_clavel_core_v1_metadata_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clavel_core_v1_artifact_proto_rawDesc), len(file_clavel_core_v1_artifact_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clavel_core_v1_artifact_proto_goTypes,
		DependencyIndexes: file_clavel_core_v1_artifact_proto_depIdxs,
		EnumInfos:         file_clavel_core_v1_artifact_proto_enumTypes,
		MessageInfos:      file_clavel_core_v1_artifact_proto_msgTypes,
	}.Build()
	File_clavel_core_v1_artifact_proto = out.File
	file_clavel_core_v1_artifact_proto_goTypes = nil
	file_clavel_core_v1_artifact_proto_depIdxs = nil
}
