// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: clavel/core/v1/custom_resource.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CustomResourceDefinition registers a new resource kind. Schemas are
// immutable once registered: reapplying an identical definition is a no-op,
// while a conflicting one is rejected.
type CustomResourceDefinition struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Group   string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Version string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Kind name, e.g. "NixosUnit". Acts as the storage key within group/version.
	Kind string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	// Plural used in resource paths, e.g. "nixosunits".
	Plural string `protobuf:"bytes,4,opt,name=plural,proto3" json:"plural,omitempty"`
	// Serialized google.protobuf.FileDescriptorSet containing the spec message.
	Schema []byte `protobuf:"bytes,5,opt,name=schema,proto3" json:"schema,omitempty"`
	// Fully-qualified message name of the spec within schema, e.g.
	// "clavel.units.nixos.v1.NixosUnitSpec".
	SpecMessage string `protobuf:"bytes,6,opt,name=spec_message,json=specMessage,proto3" json:"spec_message,omitempty"`
	// Flake reference to the action module used by the controller.
	ActionModule  string    `protobuf:"bytes,7,opt,name=action_module,json=actionModule,proto3" json:"action_module,omitempty"`
	Metadata      *Metadata `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomResourceDefinition) Reset() {
	*x = CustomResourceDefinition{}
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomResourceDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomResourceDefinition) ProtoMessage() {}

func (x *CustomResourceDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomResourceDefinition.ProtoReflect.Descriptor instead.
func (*CustomResourceDefinition) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_custom_resource_proto_rawDescGZIP(), []int{0}
}

func (x *CustomResourceDefinition) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CustomResourceDefinition) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CustomResourceDefinition) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CustomResourceDefinition) GetPlural() string {
	if x != nil {
		return x.Plural
	}
	return ""
}

func (x *CustomResourceDefinition) GetSchema() []byte {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *CustomResourceDefinition) GetSpecMessage() string {
	if x != nil {
		return x.SpecMessage
	}
	return ""
}

func (x *CustomResourceDefinition) GetActionModule() string {
	if x != nil {
		return x.ActionModule
	}
	return ""
}

func (x *CustomResourceDefinition) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Resource is an instance of a registered kind. The spec is a
// protojson-encoded message validated by clavelapi against the kind's schema.
type Resource struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Group   string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Version string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Plural  string                 `protobuf:"bytes,3,opt,name=plural,proto3" json:"plural,omitempty"`
	// Kind is derived by clavelapi from the registered CustomResourceDefinition.
	Kind          string    `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string    `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Metadata      *Metadata `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          []byte    `protobuf:"bytes,7,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_custom_resource_proto_rawDescGZIP(), []int{1}
}

func (x *Resource) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Resource) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Resource) GetPlural() string {
	if x != nil {
		return x.Plural
	}
	return ""
}

func (x *Resource) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Resource) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

type CustomResourceDefinitionServiceShowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomResourceDefinitionServiceShowRequest) Reset() {
	*x = CustomResourceDefinitionServiceShowRequest{}
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomResourceDefinitionServiceShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomResourceDefinitionServiceShowRequest) ProtoMessage() {}

func (x *CustomResourceDefinitionServiceShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomResourceDefinitionServiceShowRequest.ProtoReflect.Descriptor instead.
func (*CustomResourceDefinitionServiceShowRequest) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_custom_resource_proto_rawDescGZIP(), []int{2}
}

func (x *CustomResourceDefinitionServiceShowRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CustomResourceDefinitionServiceShowRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CustomResourceDefinitionServiceShowRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type CustomResourceDefinitionServiceShowResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Data          *CustomResourceDefinition `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomResourceDefinitionServiceShowResponse) Reset() {
	*x = CustomResourceDefinitionServiceShowResponse{}
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomResourceDefinitionServiceShowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomResourceDefinitionServiceShowResponse) ProtoMessage() {}

func (x *CustomResourceDefinitionServiceShowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomResourceDefinitionServiceShowResponse.ProtoReflect.Descriptor instead.
func (*CustomResourceDefinitionServiceShowResponse) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_custom_resource_proto_rawDescGZIP(), []int{3}
}

func (x *CustomResourceDefinitionServiceShowResponse) GetData() *CustomResourceDefinition {
	if x != nil {
		return x.Data
	}
	return nil
}

type CustomResourceDefinitionServiceListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomResourceDefinitionServiceListRequest) Reset() {
	*x = CustomResourceDefinitionServiceListRequest{}
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomResourceDefinitionServiceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomResourceDefinitionServiceListRequest) ProtoMessage() {}

func (x *CustomResourceDefinitionServiceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomResourceDefinitionServiceListRequest.ProtoReflect.Descriptor instead.
func (*CustomResourceDefinitionServiceListRequest) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_custom_resource_proto_rawDescGZIP(), []int{4}
}

type CustomResourceDefinitionServiceListResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Data          []*CustomResourceDefinition `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomResourceDefinitionServiceListResponse) Reset() {
	*x = CustomResourceDefinitionServiceListResponse{}
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomResourceDefinitionServiceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomResourceDefinitionServiceListResponse) ProtoMessage() {}

func (x *CustomResourceDefinitionServiceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomResourceDefinitionServiceListResponse.ProtoReflect.Descriptor instead.
func (*CustomResourceDefinitionServiceListResponse) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_custom_resource_proto_rawDescGZIP(), []int{5}
}

func (x *CustomResourceDefinitionServiceListResponse) GetData() []*CustomResourceDefinition {
	if x != nil {
		return x.Data
	}
	return nil
}

type CustomResourceDefinitionServiceCreateRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Data          *CustomResourceDefinition `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomResourceDefinitionServiceCreateRequest) Reset() {
	*x = CustomResourceDefinitionServiceCreateRequest{}
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomResourceDefinitionServiceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomResourceDefinitionServiceCreateRequest) ProtoMessage() {}

func (x *CustomResourceDefinitionServiceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomResourceDefinitionServiceCreateRequest.ProtoReflect.Descriptor instead.
func (*CustomResourceDefinitionServiceCreateRequest) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_custom_resource_proto_rawDescGZIP(), []int{6}
}

func (x *CustomResourceDefinitionServiceCreateRequest) GetData() *CustomResourceDefinition {
	if x != nil {
		return x.Data
	}
	return nil
}

type CustomResourceDefinitionServiceCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomResourceDefinitionServiceCreateResponse) Reset() {
	*x = CustomResourceDefinitionServiceCreateResponse{}
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomResourceDefinitionServiceCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomResourceDefinitionServiceCreateResponse) ProtoMessage() {}

func (x *CustomResourceDefinitionServiceCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomResourceDefinitionServiceCreateResponse.ProtoReflect.Descriptor instead.
func (*CustomResourceDefinitionServiceCreateResponse) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_custom_resource_proto_rawDescGZIP(), []int{7}
}

type CustomResourceDefinitionServiceDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomResourceDefinitionServiceDeleteRequest) Reset() {
	*x = CustomResourceDefinitionServiceDeleteRequest{}
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomResourceDefinitionServiceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomResourceDefinitionServiceDeleteRequest) ProtoMessage() {}

func (x *CustomResourceDefinitionServiceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomResourceDefinitionServiceDeleteRequest.ProtoReflect.Descriptor instead.
func (*CustomResourceDefinitionServiceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_custom_resource_proto_rawDescGZIP(), []int{8}
}

func (x *CustomResourceDefinitionServiceDeleteRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CustomResourceDefinitionServiceDeleteRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CustomResourceDefinitionServiceDeleteRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type CustomResourceDefinitionServiceDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomResourceDefinitionServiceDeleteResponse) Reset() {
	*x = CustomResourceDefinitionServiceDeleteResponse{}
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomResourceDefinitionServiceDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomResourceDefinitionServiceDeleteResponse) ProtoMessage() {}

func (x *CustomResourceDefinitionServiceDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomResourceDefinitionServiceDeleteResponse.ProtoReflect.Descriptor instead.
func (*CustomResourceDefinitionServiceDeleteResponse) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_custom_resource_proto_rawDescGZIP(), []int{9}
}

type CustomResourceDefinitionServiceWatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          bool                   `protobuf:"varint,1,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomResourceDefinitionServiceWatchRequest) Reset() {
	*x = CustomResourceDefinitionServiceWatchRequest{}
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomResourceDefinitionServiceWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomResourceDefinitionServiceWatchRequest) ProtoMessage() {}

func (x *CustomResourceDefinitionServiceWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomResourceDefinitionServiceWatchRequest.ProtoReflect.Descriptor instead.
func (*CustomResourceDefinitionServiceWatchRequest) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_custom_resource_proto_rawDescGZIP(), []int{10}
}

func (x *CustomResourceDefinitionServiceWatchRequest) GetList() bool {
	if x != nil {
		return x.List
	}
	return false
}

type CustomResourceDefinitionServiceWatchResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Data          *CustomResourceDefinition `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error         *Error                    `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomResourceDefinitionServiceWatchResponse) Reset() {
	*x = CustomResourceDefinitionServiceWatchResponse{}
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomResourceDefinitionServiceWatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomResourceDefinitionServiceWatchResponse) ProtoMessage() {}

func (x *CustomResourceDefinitionServiceWatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomResourceDefinitionServiceWatchResponse.ProtoReflect.Descriptor instead.
func (*CustomResourceDefinitionServiceWatchResponse) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_custom_resource_proto_rawDescGZIP(), []int{11}
}

func (x *CustomResourceDefinitionServiceWatchResponse) GetData() *CustomResourceDefinition {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CustomResourceDefinitionServiceWatchResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type CustomResourceServiceShowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Plural        string                 `protobuf:"bytes,3,opt,name=plural,proto3" json:"plural,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomResourceServiceShowRequest) Reset() {
	*x = CustomResourceServiceShowRequest{}
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomResourceServiceShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomResourceServiceShowRequest) ProtoMessage() {}

func (x *CustomResourceServiceShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomResourceServiceShowRequest.ProtoReflect.Descriptor instead.
func (*CustomResourceServiceShowRequest) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_custom_resource_proto_rawDescGZIP(), []int{12}
}

func (x *CustomResourceServiceShowRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CustomResourceServiceShowRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CustomResourceServiceShowRequest) GetPlural() string {
	if x != nil {
		return x.Plural
	}
	return ""
}

func (x *CustomResourceServiceShowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CustomResourceServiceShowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Resource              `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomResourceServiceShowResponse) Reset() {
	*x = CustomResourceServiceShowResponse{}
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomResourceServiceShowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomResourceServiceShowResponse) ProtoMessage() {}

func (x *CustomResourceServiceShowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomResourceServiceShowResponse.ProtoReflect.Descriptor instead.
func (*CustomResourceServiceShowResponse) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_custom_resource_proto_rawDescGZIP(), []int{13}
}

func (x *CustomResourceServiceShowResponse) GetData() *Resource {
	if x != nil {
		return x.Data
	}
	return nil
}

type CustomResourceServiceListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Plural        string                 `protobuf:"bytes,3,opt,name=plural,proto3" json:"plural,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomResourceServiceListRequest) Reset() {
	*x = CustomResourceServiceListRequest{}
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomResourceServiceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomResourceServiceListRequest) ProtoMessage() {}

func (x *CustomResourceServiceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomResourceServiceListRequest.ProtoReflect.Descriptor instead.
func (*CustomResourceServiceListRequest) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_custom_resource_proto_rawDescGZIP(), []int{14}
}

func (x *CustomResourceServiceListRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CustomResourceServiceListRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CustomResourceServiceListRequest) GetPlural() string {
	if x != nil {
		return x.Plural
	}
	return ""
}

type CustomResourceServiceListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Resource            `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomResourceServiceListResponse) Reset() {
	*x = CustomResourceServiceListResponse{}
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomResourceServiceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomResourceServiceListResponse) ProtoMessage() {}

func (x *CustomResourceServiceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomResourceServiceListResponse.ProtoReflect.Descriptor instead.
func (*CustomResourceServiceListResponse) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_custom_resource_proto_rawDescGZIP(), []int{15}
}

func (x *CustomResourceServiceListResponse) GetData() []*Resource {
	if x != nil {
		return x.Data
	}
	return nil
}

type CustomResourceServiceCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Resource              `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomResourceServiceCreateRequest) Reset() {
	*x = CustomResourceServiceCreateRequest{}
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomResourceServiceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomResourceServiceCreateRequest) ProtoMessage() {}

func (x *CustomResourceServiceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomResourceServiceCreateRequest.ProtoReflect.Descriptor instead.
func (*CustomResourceServiceCreateRequest) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_custom_resource_proto_rawDescGZIP(), []int{16}
}

func (x *CustomResourceServiceCreateRequest) GetData() *Resource {
	if x != nil {
		return x.Data
	}
	return nil
}

type CustomResourceServiceCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomResourceServiceCreateResponse) Reset() {
	*x = CustomResourceServiceCreateResponse{}
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomResourceServiceCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomResourceServiceCreateResponse) ProtoMessage() {}

func (x *CustomResourceServiceCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomResourceServiceCreateResponse.ProtoReflect.Descriptor instead.
func (*CustomResourceServiceCreateResponse) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_custom_resource_proto_rawDescGZIP(), []int{17}
}

type CustomResourceServiceUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Plural        string                 `protobuf:"bytes,3,opt,name=plural,proto3" json:"plural,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Data          *Resource              `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,6,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomResourceServiceUpdateRequest) Reset() {
	*x = CustomResourceServiceUpdateRequest{}
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomResourceServiceUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomResourceServiceUpdateRequest) ProtoMessage() {}

func (x *CustomResourceServiceUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomResourceServiceUpdateRequest.ProtoReflect.Descriptor instead.
func (*CustomResourceServiceUpdateRequest) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_custom_resource_proto_rawDescGZIP(), []int{18}
}

func (x *CustomResourceServiceUpdateRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CustomResourceServiceUpdateRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CustomResourceServiceUpdateRequest) GetPlural() string {
	if x != nil {
		return x.Plural
	}
	return ""
}

func (x *CustomResourceServiceUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomResourceServiceUpdateRequest) GetData() *Resource {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CustomResourceServiceUpdateRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type CustomResourceServiceUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomResourceServiceUpdateResponse) Reset() {
	*x = CustomResourceServiceUpdateResponse{}
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomResourceServiceUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomResourceServiceUpdateResponse) ProtoMessage() {}

func (x *CustomResourceServiceUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomResourceServiceUpdateResponse.ProtoReflect.Descriptor instead.
func (*CustomResourceServiceUpdateResponse) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_custom_resource_proto_rawDescGZIP(), []int{19}
}

type CustomResourceServiceDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Plural        string                 `protobuf:"bytes,3,opt,name=plural,proto3" json:"plural,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomResourceServiceDeleteRequest) Reset() {
	*x = CustomResourceServiceDeleteRequest{}
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomResourceServiceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomResourceServiceDeleteRequest) ProtoMessage() {}

func (x *CustomResourceServiceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomResourceServiceDeleteRequest.ProtoReflect.Descriptor instead.
func (*CustomResourceServiceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_custom_resource_proto_rawDescGZIP(), []int{20}
}

func (x *CustomResourceServiceDeleteRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CustomResourceServiceDeleteRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CustomResourceServiceDeleteRequest) GetPlural() string {
	if x != nil {
		return x.Plural
	}
	return ""
}

func (x *CustomResourceServiceDeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CustomResourceServiceDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomResourceServiceDeleteResponse) Reset() {
	*x = CustomResourceServiceDeleteResponse{}
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomResourceServiceDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomResourceServiceDeleteResponse) ProtoMessage() {}

func (x *CustomResourceServiceDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomResourceServiceDeleteResponse.ProtoReflect.Descriptor instead.
func (*CustomResourceServiceDeleteResponse) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_custom_resource_proto_rawDescGZIP(), []int{21}
}

type CustomResourceServiceWatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Plural        string                 `protobuf:"bytes,3,opt,name=plural,proto3" json:"plural,omitempty"`
	List          bool                   `protobuf:"varint,4,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomResourceServiceWatchRequest) Reset() {
	*x = CustomResourceServiceWatchRequest{}
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomResourceServiceWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomResourceServiceWatchRequest) ProtoMessage() {}

func (x *CustomResourceServiceWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomResourceServiceWatchRequest.ProtoReflect.Descriptor instead.
func (*CustomResourceServiceWatchRequest) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_custom_resource_proto_rawDescGZIP(), []int{22}
}

func (x *CustomResourceServiceWatchRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CustomResourceServiceWatchRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CustomResourceServiceWatchRequest) GetPlural() string {
	if x != nil {
		return x.Plural
	}
	return ""
}

func (x *CustomResourceServiceWatchRequest) GetList() bool {
	if x != nil {
		return x.List
	}
	return false
}

type CustomResourceServiceWatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Resource              `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomResourceServiceWatchResponse) Reset() {
	*x = CustomResourceServiceWatchResponse{}
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomResourceServiceWatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomResourceServiceWatchResponse) ProtoMessage() {}

func (x *CustomResourceServiceWatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_custom_resource_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomResourceServiceWatchResponse.ProtoReflect.Descriptor instead.
func (*CustomResourceServiceWatchResponse) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_custom_resource_proto_rawDescGZIP(), []int{23}
}

func (x *CustomResourceServiceWatchResponse) GetData() *Resource {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CustomResourceServiceWatchResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_clavel_core_v1_custom_resource_proto protoreflect.FileDescriptor

const file_clavel_core_v1_custom_resource_proto_rawDesc = "" +
	"\n" +
	"$clavel/core/v1/custom_resource.proto\x12\x0eclavel.core.v1\x1a\x1fclavel/core/v1/evaluation.proto\x1a\x1dclavel/core/v1/metadata.proto\x1a google/protobuf/field_mask.proto\"\x8c\x02\n" +
	"\x18CustomResourceDefinition\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x16\n" +
	"\x06plural\x18\x04 \x01(\tR\x06plural\x12\x16\n" +
	"\x06schema\x18\x05 \x01(\fR\x06schema\x12!\n" +
	"\fspec_message\x18\x06 \x01(\tR\vspecMessage\x12#\n" +
	"\raction_module\x18\a \x01(\tR\factionModule\x124\n" +
	"\bmetadata\x18\b \x01(\v2\x18.clavel.core.v1.MetadataR\bmetadata\"\xc4\x01\n" +
	"\bResource\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06plural\x18\x03 \x01(\tR\x06plural\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x124\n" +
	"\bmetadata\x18\x06 \x01(\v2\x18.clavel.core.v1.MetadataR\bmetadata\x12\x12\n" +
	"\x04spec\x18\a \x01(\fR\x04spec\"p\n" +
	"*CustomResourceDefinitionServiceShowRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\"k\n" +
	"+CustomResourceDefinitionServiceShowResponse\x12<\n" +
	"\x04data\x18\x01 \x01(\v2(.clavel.core.v1.CustomResourceDefinitionR\x04data\",\n" +
	"*CustomResourceDefinitionServiceListRequest\"k\n" +
	"+CustomResourceDefinitionServiceListResponse\x12<\n" +
	"\x04data\x18\x01 \x03(\v2(.clavel.core.v1.CustomResourceDefinitionR\x04data\"l\n" +
	",CustomResourceDefinitionServiceCreateRequest\x12<\n" +
	"\x04data\x18\x01 \x01(\v2(.clavel.core.v1.CustomResourceDefinitionR\x04data\"/\n" +
	"-CustomResourceDefinitionServiceCreateResponse\"r\n" +
	",CustomResourceDefinitionServiceDeleteRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\"/\n" +
	"-CustomResourceDefinitionServiceDeleteResponse\"A\n" +
	"+CustomResourceDefinitionServiceWatchRequest\x12\x12\n" +
	"\x04list\x18\x01 \x01(\bR\x04list\"\x99\x01\n" +
	",CustomResourceDefinitionServiceWatchResponse\x12<\n" +
	"\x04data\x18\x01 \x01(\v2(.clavel.core.v1.CustomResourceDefinitionR\x04data\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x15.clavel.core.v1.ErrorR\x05error\"~\n" +
	" CustomResourceServiceShowRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06plural\x18\x03 \x01(\tR\x06plural\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"Q\n" +
	"!CustomResourceServiceShowResponse\x12,\n" +
	"\x04data\x18\x01 \x01(\v2\x18.clavel.core.v1.ResourceR\x04data\"j\n" +
	" CustomResourceServiceListRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06plural\x18\x03 \x01(\tR\x06plural\"Q\n" +
	"!CustomResourceServiceListResponse\x12,\n" +
	"\x04data\x18\x01 \x03(\v2\x18.clavel.core.v1.ResourceR\x04data\"R\n" +
	"\"CustomResourceServiceCreateRequest\x12,\n" +
	"\x04data\x18\x01 \x01(\v2\x18.clavel.core.v1.ResourceR\x04data\"%\n" +
	"#CustomResourceServiceCreateResponse\"\xeb\x01\n" +
	"\"CustomResourceServiceUpdateRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06plural\x18\x03 \x01(\tR\x06plural\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12,\n" +
	"\x04data\x18\x05 \x01(\v2\x18.clavel.core.v1.ResourceR\x04data\x12;\n" +
	"\vupdate_mask\x18\x06 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"%\n" +
	"#CustomResourceServiceUpdateResponse\"\x80\x01\n" +
	"\"CustomResourceServiceDeleteRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06plural\x18\x03 \x01(\tR\x06plural\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"%\n" +
	"#CustomResourceServiceDeleteResponse\"\x7f\n" +
	"!CustomResourceServiceWatchRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06plural\x18\x03 \x01(\tR\x06plural\x12\x12\n" +
	"\x04list\x18\x04 \x01(\bR\x04list\"\x7f\n" +
	"\"CustomResourceServiceWatchResponse\x12,\n" +
	"\x04data\x18\x01 \x01(\v2\x18.clavel.core.v1.ResourceR\x04data\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x15.clavel.core.v1.ErrorR\x05error2\xc6\x05\n" +
	"\x1fCustomResourceDefinitionService\x12\x81\x01\n" +
	"\x04Show\x12:.clavel.core.v1.CustomResourceDefinitionServiceShowRequest\x1a;.clavel.core.v1.CustomResourceDefinitionServiceShowResponse\"\x00\x12\x81\x01\n" +
	"\x04List\x12:.clavel.core.v1.CustomResourceDefinitionServiceListRequest\x1a;.clavel.core.v1.CustomResourceDefinitionServiceListResponse\"\x00\x12\x87\x01\n" +
	"\x06Create\x12<.clavel.core.v1.CustomResourceDefinitionServiceCreateRequest\x1a=.clavel.core.v1.CustomResourceDefinitionServiceCreateResponse\"\x00\x12\x87\x01\n" +
	"\x06Delete\x12<.clavel.core.v1.CustomResourceDefinitionServiceDeleteRequest\x1a=.clavel.core.v1.CustomResourceDefinitionServiceDeleteResponse\"\x00\x12\x86\x01\n" +
	"\x05Watch\x12;.clavel.core.v1.CustomResourceDefinitionServiceWatchRequest\x1a<.clavel.core.v1.CustomResourceDefinitionServiceWatchResponse\"\x000\x012\xc8\x05\n" +
	"\x15CustomResourceService\x12m\n" +
	"\x04Show\x120.clavel.core.v1.CustomResourceServiceShowRequest\x1a1.clavel.core.v1.CustomResourceServiceShowResponse\"\x00\x12m\n" +
	"\x04List\x120.clavel.core.v1.CustomResourceServiceListRequest\x1a1.clavel.core.v1.CustomResourceServiceListResponse\"\x00\x12s\n" +
	"\x06Create\x122.clavel.core.v1.CustomResourceServiceCreateRequest\x1a3.clavel.core.v1.CustomResourceServiceCreateResponse\"\x00\x12s\n" +
	"\x06Update\x122.clavel.core.v1.CustomResourceServiceUpdateRequest\x1a3.clavel.core.v1.CustomResourceServiceUpdateResponse\"\x00\x12s\n" +
	"\x06Delete\x122.clavel.core.v1.CustomResourceServiceDeleteRequest\x1a3.clavel.core.v1.CustomResourceServiceDeleteResponse\"\x00\x12r\n" +
	"\x05Watch\x121.clavel.core.v1.CustomResourceServiceWatchRequest\x1a2.clavel.core.v1.CustomResourceServiceWatchResponse\"\x000\x01B2Z0github.com/erikeah/clavel/pkg/api/core/v1;corev1b\x06proto3"

var (
	file_clavel_core_v1_custom_resource_proto_rawDescOnce sync.Once
	file_clavel_core_v1_custom_resource_proto_rawDescData []byte
)

func file_clavel_core_v1_custom_resource_proto_rawDescGZIP() []byte {
	file_clavel_core_v1_custom_resource_proto_rawDescOnce.Do(func() {
		file_clavel_core_v1_custom_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clavel_core_v1_custom_resource_proto_rawDesc), len(file_clavel_core_v1_custom_resource_proto_rawDesc)))
	})
	return file_clavel_core_v1_custom_resource_proto_rawDescData
}

var file_clavel_core_v1_custom_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_clavel_core_v1_custom_resource_proto_goTypes = []any{
	(*CustomResourceDefinition)(nil),                      // 0: clavel.core.v1.CustomResourceDefinition
	(*Resource)(nil),                                      // 1: clavel.core.v1.Resource
	(*CustomResourceDefinitionServiceShowRequest)(nil),    // 2: clavel.core.v1.CustomResourceDefinitionServiceShowRequest
	(*CustomResourceDefinitionServiceShowResponse)(nil),   // 3: clavel.core.v1.CustomResourceDefinitionServiceShowResponse
	(*CustomResourceDefinitionServiceListRequest)(nil),    // 4: clavel.core.v1.CustomResourceDefinitionServiceListRequest
	(*CustomResourceDefinitionServiceListResponse)(nil),   // 5: clavel.core.v1.CustomResourceDefinitionServiceListResponse
	(*CustomResourceDefinitionServiceCreateRequest)(nil),  // 6: clavel.core.v1.CustomResourceDefinitionServiceCreateRequest
	(*CustomResourceDefinitionServiceCreateResponse)(nil), // 7: clavel.core.v1.CustomResourceDefinitionServiceCreateResponse
	(*CustomResourceDefinitionServiceDeleteRequest)(nil),  // 8: clavel.core.v1.CustomResourceDefinitionServiceDeleteRequest
	(*CustomResourceDefinitionServiceDeleteResponse)(nil), // 9: clavel.core.v1.CustomResourceDefinitionServiceDeleteResponse
	(*CustomResourceDefinitionServiceWatchRequest)(nil),   // 10: clavel.core.v1.CustomResourceDefinitionServiceWatchRequest
	(*CustomResourceDefinitionServiceWatchResponse)(nil),  // 11: clavel.core.v1.CustomResourceDefinitionServiceWatchResponse
	(*CustomResourceServiceShowRequest)(nil),              // 12: clavel.core.v1.CustomResourceServiceShowRequest
	(*CustomResourceServiceShowResponse)(nil),             // 13: clavel.core.v1.CustomResourceServiceShowResponse
	(*CustomResourceServiceListRequest)(nil),              // 14: clavel.core.v1.CustomResourceServiceListRequest
	(*CustomResourceServiceListResponse)(nil),             // 15: clavel.core.v1.CustomResourceServiceListResponse
	(*CustomResourceServiceCreateRequest)(nil),            // 16: clavel.core.v1.CustomResourceServiceCreateRequest
	(*CustomResourceServiceCreateResponse)(nil),           // 17: clavel.core.v1.CustomResourceServiceCreateResponse
	(*CustomResourceServiceUpdateRequest)(nil),            // 18: clavel.core.v1.CustomResourceServiceUpdateRequest
	(*CustomResourceServiceUpdateResponse)(nil),           // 19: clavel.core.v1.CustomResourceServiceUpdateResponse
	(*CustomResourceServiceDeleteRequest)(nil),            // 20: clavel.core.v1.CustomResourceServiceDeleteRequest
	(*CustomResourceServiceDeleteResponse)(nil),           // 21: clavel.core.v1.CustomResourceServiceDeleteResponse
	(*CustomResourceServiceWatchRequest)(nil),             // 22: clavel.core.v1.CustomResourceServiceWatchRequest
	(*CustomResourceServiceWatchResponse)(nil),            // 23: clavel.core.v1.CustomResourceServiceWatchResponse
	(*Metadata)(nil),              // 24: clavel.core.v1.Metadata
	(*Error)(nil),                 // 25: clavel.core.v1.Error
	(*fieldmaskpb.FieldMask)(nil), // 26: google.protobuf.FieldMask
}
var file_clavel_core_v1_custom_resource_proto_depIdxs = []int32{
	24, // 0: clavel.core.v1.CustomResourceDefinition.metadata:type_name -> clavel.core.v1.Metadata
	24, // 1: clavel.core.v1.Resource.metadata:type_name -> clavel.core.v1.Metadata
	0,  // 2: clavel.core.v1.CustomResourceDefinitionServiceShowResponse.data:type_name -> clavel.core.v1.CustomResourceDefinition
	0,  // 3: clavel.core.v1.CustomResourceDefinitionServiceListResponse.data:type_name -> clavel.core.v1.CustomResourceDefinition
	0,  // 4: clavel.core.v1.CustomResourceDefinitionServiceCreateRequest.data:type_name -> clavel.core.v1.CustomResourceDefinition
	0,  // 5: clavel.core.v1.CustomResourceDefinitionServiceWatchResponse.data:type_name -> clavel.core.v1.CustomResourceDefinition
	25, // 6: clavel.core.v1.CustomResourceDefinitionServiceWatchResponse.error:type_name -> clavel.core.v1.Error
	1,  // 7: clavel.core.v1.CustomResourceServiceShowResponse.data:type_name -> clavel.core.v1.Resource
	1,  // 8: clavel.core.v1.CustomResourceServiceListResponse.data:type_name -> clavel.core.v1.Resource
	1,  // 9: clavel.core.v1.CustomResourceServiceCreateRequest.data:type_name -> clavel.core.v1.Resource
	1,  // 10: clavel.core.v1.CustomResourceServiceUpdateRequest.data:type_name -> clavel.core.v1.Resource
	26, // 11: clavel.core.v1.CustomResourceServiceUpdateRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 12: clavel.core.v1.CustomResourceServiceWatchResponse.data:type_name -> clavel.core.v1.Resource
	25, // 13: clavel.core.v1.CustomResourceServiceWatchResponse.error:type_name -> clavel.core.v1.Error
	2,  // 14: clavel.core.v1.CustomResourceDefinitionService.Show:input_type -> clavel.core.v1.CustomResourceDefinitionServiceShowRequest
	4,  // 15: clavel.core.v1.CustomResourceDefinitionService.List:input_type -> clavel.core.v1.CustomResourceDefinitionServiceListRequest
	6,  // 16: clavel.core.v1.CustomResourceDefinitionService.Create:input_type -> clavel.core.v1.CustomResourceDefinitionServiceCreateRequest
	8,  // 17: clavel.core.v1.CustomResourceDefinitionService.Delete:input_type -> clavel.core.v1.CustomResourceDefinitionServiceDeleteRequest
	10, // 18: clavel.core.v1.CustomResourceDefinitionService.Watch:input_type -> clavel.core.v1.CustomResourceDefinitionServiceWatchRequest
	12, // 19: clavel.core.v1.CustomResourceService.Show:input_type -> clavel.core.v1.CustomResourceServiceShowRequest
	14, // 20: clavel.core.v1.CustomResourceService.List:input_type -> clavel.core.v1.CustomResourceServiceListRequest
	16, // 21: clavel.core.v1.CustomResourceService.Create:input_type -> clavel.core.v1.CustomResourceServiceCreateRequest
	18, // 22: clavel.core.v1.CustomResourceService.Update:input_type -> clavel.core.v1.CustomResourceServiceUpdateRequest
	20, // 23: clavel.core.v1.CustomResourceService.Delete:input_type -> clavel.core.v1.CustomResourceServiceDeleteRequest
	22, // 24: clavel.core.v1.CustomResourceService.Watch:input_type -> clavel.core.v1.CustomResourceServiceWatchRequest
	3,  // 25: clavel.core.v1.CustomResourceDefinitionService.Show:output_type -> clavel.core.v1.CustomResourceDefinitionServiceShowResponse
	5,  // 26: clavel.core.v1.CustomResourceDefinitionService.List:output_type -> clavel.core.v1.CustomResourceDefinitionServiceListResponse
	7,  // 27: clavel.core.v1.CustomResourceDefinitionService.Create:output_type -> clavel.core.v1.CustomResourceDefinitionServiceCreateResponse
	9,  // 28: clavel.core.v1.CustomResourceDefinitionService.Delete:output_type -> clavel.core.v1.CustomResourceDefinitionServiceDeleteResponse
	11, // 29: clavel.core.v1.CustomResourceDefinitionService.Watch:output_type -> clavel.core.v1.CustomResourceDefinitionServiceWatchResponse
	13, // 30: clavel.core.v1.CustomResourceService.Show:output_type -> clavel.core.v1.CustomResourceServiceShowResponse
	15, // 31: clavel.core.v1.CustomResourceService.List:output_type -> clavel.core.v1.CustomResourceServiceListResponse
	17, // 32: clavel.core.v1.CustomResourceService.Create:output_type -> clavel.core.v1.CustomResourceServiceCreateResponse
	19, // 33: clavel.core.v1.CustomResourceService.Update:output_type -> clavel.core.v1.CustomResourceServiceUpdateResponse
	21, // 34: clavel.core.v1.CustomResourceService.Delete:output_type -> clavel.core.v1.CustomResourceServiceDeleteResponse
	23, // 35: clavel.core.v1.CustomResourceService.Watch:output_type -> clavel.core.v1.CustomResourceServiceWatchResponse
	25, // [25:36] is the sub-list for method output_type
	14, // [14:25] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_clavel_core_v1_custom_resource_proto_init() }
func file_clavel_core_v1_custom_resource_proto_init() {
	if File_clavel_core_v1_custom_resource_proto != nil {
		return
	}
	file_clavel_core_v1_evaluation_proto_init()
	file_clavel_core_v1_metadata_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clavel_core_v1_custom_resource_proto_rawDesc), len(file_clavel_core_v1_custom_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_clavel_core_v1_custom_resource_proto_goTypes,
		DependencyIndexes: file_clavel_core_v1_custom_resource_proto_depIdxs,
		MessageInfos:      file_clavel_core_v1_custom_resource_proto_msgTypes,
	}.Build()
	File_clavel_core_v1_custom_resource_proto = out.File
	file_clavel_core_v1_custom_resource_proto_goTypes = nil
	file_clavel_core_v1_custom_resource_proto_depIdxs = nil
}
