// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: clavel/core/v1/event.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType describes how a watched resource changed. Shared by every Watch
// RPC so resource kinds agree on the vocabulary.
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	// A resource exists (initial snapshot item or a create/update).
	EventType_EVENT_TYPE_PUT EventType = 1
	// A resource was removed; only the identity is carried, never the object.
	EventType_EVENT_TYPE_DELETE EventType = 2
	// The initial snapshot ended; everything sent before this marker was the
	// state at connect time, everything after it is a change.
	EventType_EVENT_TYPE_SYNC EventType = 3
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_PUT",
		2: "EVENT_TYPE_DELETE",
		3: "EVENT_TYPE_SYNC",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"EVENT_TYPE_PUT":         1,
		"EVENT_TYPE_DELETE":      2,
		"EVENT_TYPE_SYNC":        3,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_clavel_core_v1_event_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_clavel_core_v1_event_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_clavel_core_v1_event_proto_rawDescGZIP(), []int{0}
}

var File_clavel_core_v1_event_proto protoreflect.FileDescriptor

const file_clavel_core_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x1aclavel/core/v1/event.proto\x12\x0eclavel.core.v1*g\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eEVENT_TYPE_PUT\x10\x01\x12\x15\n" +
	"\x11EVENT_TYPE_DELETE\x10\x02\x12\x13\n" +
	"\x0fEVENT_TYPE_SYNC\x10\x03B2Z0github.com/erikeah/clavel/pkg/api/core/v1;corev1b\x06proto3"

var (
	file_clavel_core_v1_event_proto_rawDescOnce sync.Once
	file_clavel_core_v1_event_proto_rawDescData []byte
)

func file_clavel_core_v1_event_proto_rawDescGZIP() []byte {
	file_clavel_core_v1_event_proto_rawDescOnce.Do(func() {
		file_clavel_core_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clavel_core_v1_event_proto_rawDesc), len(file_clavel_core_v1_event_proto_rawDesc)))
	})
	return file_clavel_core_v1_event_proto_rawDescData
}

var file_clavel_core_v1_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_clavel_core_v1_event_proto_goTypes = []any{
	(EventType)(0), // 0: clavel.core.v1.EventType
}
var file_clavel_core_v1_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clavel_core_v1_event_proto_init() }
func file_clavel_core_v1_event_proto_init() {
	if File_clavel_core_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clavel_core_v1_event_proto_rawDesc), len(file_clavel_core_v1_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clavel_core_v1_event_proto_goTypes,
		DependencyIndexes: file_clavel_core_v1_event_proto_depIdxs,
		EnumInfos:         file_clavel_core_v1_event_proto_enumTypes,
	}.Build()
	File_clavel_core_v1_event_proto = out.File
	file_clavel_core_v1_event_proto_goTypes = nil
	file_clavel_core_v1_event_proto_depIdxs = nil
}
