// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: clavel/core/v1/metadata.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metadata struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Generation        uint32                 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	CreationTimestamp string                 `protobuf:"bytes,2,opt,name=creation_timestamp,json=creationTimestamp,proto3" json:"creation_timestamp,omitempty"`
	DeletionTimestamp string                 `protobuf:"bytes,3,opt,name=deletion_timestamp,json=deletionTimestamp,proto3" json:"deletion_timestamp,omitempty"`
	Finalizers        []string               `protobuf:"bytes,4,rep,name=finalizers,proto3" json:"finalizers,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_clavel_core_v1_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_core_v1_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_clavel_core_v1_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Metadata) GetCreationTimestamp() string {
	if x != nil {
		return x.CreationTimestamp
	}
	return ""
}

func (x *Metadata) GetDeletionTimestamp() string {
	if x != nil {
		return x.DeletionTimestamp
	}
	return ""
}

func (x *Metadata) GetFinalizers() []string {
	if x != nil {
		return x.Finalizers
	}
	return nil
}

var File_clavel_core_v1_metadata_proto protoreflect.FileDescriptor

const file_clavel_core_v1_metadata_proto_rawDesc = "" +
	"\n" +
	"\x1dclavel/core/v1/metadata.proto\x12\x0eclavel.core.v1\"\xa8\x01\n" +
	"\bMetadata\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\rR\n" +
	"generation\x12-\n" +
	"\x12creation_timestamp\x18\x02 \x01(\tR\x11creationTimestamp\x12-\n" +
	"\x12deletion_timestamp\x18\x03 \x01(\tR\x11deletionTimestamp\x12\x1e\n" +
	"\n" +
	"finalizers\x18\x04 \x03(\tR\n" +
	"finalizersB2Z0github.com/erikeah/clavel/pkg/api/core/v1;corev1b\x06proto3"

var (
	file_clavel_core_v1_metadata_proto_rawDescOnce sync.Once
	file_clavel_core_v1_metadata_proto_rawDescData []byte
)

func file_clavel_core_v1_metadata_proto_rawDescGZIP() []byte {
	file_clavel_core_v1_metadata_proto_rawDescOnce.Do(func() {
		file_clavel_core_v1_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clavel_core_v1_metadata_proto_rawDesc), len(file_clavel_core_v1_metadata_proto_rawDesc)))
	})
	return file_clavel_core_v1_metadata_proto_rawDescData
}

var file_clavel_core_v1_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_clavel_core_v1_metadata_proto_goTypes = []any{
	(*Metadata)(nil), // 0: clavel.core.v1.Metadata
}
var file_clavel_core_v1_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clavel_core_v1_metadata_proto_init() }
func file_clavel_core_v1_metadata_proto_init() {
	if File_clavel_core_v1_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clavel_core_v1_metadata_proto_rawDesc), len(file_clavel_core_v1_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clavel_core_v1_metadata_proto_goTypes,
		DependencyIndexes: file_clavel_core_v1_metadata_proto_depIdxs,
		MessageInfos:      file_clavel_core_v1_metadata_proto_msgTypes,
	}.Build()
	File_clavel_core_v1_metadata_proto = out.File
	file_clavel_core_v1_metadata_proto_goTypes = nil
	file_clavel_core_v1_metadata_proto_depIdxs = nil
}
