// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: clavel/units/nixos/v1/nixos_unit.proto

package nixosv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NixosUnitSpec is the spec of a NixosUnit custom resource. It references an
// Evaluation whose flake reference yields a NixOS toplevel derivation.
type NixosUnitSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the referenced Evaluation.
	Evaluation string `protobuf:"bytes,1,opt,name=evaluation,proto3" json:"evaluation,omitempty"`
	// System profile to activate, e.g. "/nix/var/nix/profiles/system".
	Profile       string      `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	Strategies    []*Strategy `protobuf:"bytes,3,rep,name=strategies,proto3" json:"strategies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NixosUnitSpec) Reset() {
	*x = NixosUnitSpec{}
	mi := &file_clavel_units_nixos_v1_nixos_unit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NixosUnitSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NixosUnitSpec) ProtoMessage() {}

func (x *NixosUnitSpec) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_units_nixos_v1_nixos_unit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NixosUnitSpec.ProtoReflect.Descriptor instead.
func (*NixosUnitSpec) Descriptor() ([]byte, []int) {
	return file_clavel_units_nixos_v1_nixos_unit_proto_rawDescGZIP(), []int{0}
}

func (x *NixosUnitSpec) GetEvaluation() string {
	if x != nil {
		return x.Evaluation
	}
	return ""
}

func (x *NixosUnitSpec) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *NixosUnitSpec) GetStrategies() []*Strategy {
	if x != nil {
		return x.Strategies
	}
	return nil
}

type Strategy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deployment strategy type, e.g. "local" or "ssh".
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Target host for remote strategies.
	Host          string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Strategy) Reset() {
	*x = Strategy{}
	mi := &file_clavel_units_nixos_v1_nixos_unit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Strategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Strategy) ProtoMessage() {}

func (x *Strategy) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_units_nixos_v1_nixos_unit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Strategy.ProtoReflect.Descriptor instead.
func (*Strategy) Descriptor() ([]byte, []int) {
	return file_clavel_units_nixos_v1_nixos_unit_proto_rawDescGZIP(), []int{1}
}

func (x *Strategy) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Strategy) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

var File_clavel_units_nixos_v1_nixos_unit_proto protoreflect.FileDescriptor

const file_clavel_units_nixos_v1_nixos_unit_proto_rawDesc = "" +
	"\n" +
	"&clavel/units/nixos/v1/nixos_unit.proto\x12\x15clavel.units.nixos.v1\"\x8a\x01\n" +
	"\rNixosUnitSpec\x12\x1e\n" +
	"\n" +
	"evaluation\x18\x01 \x01(\tR\n" +
	"evaluation\x12\x18\n" +
	"\aprofile\x18\x02 \x01(\tR\aprofile\x12?\n" +
	"\n" +
	"strategies\x18\x03 \x03(\v2\x1f.clavel.units.nixos.v1.StrategyR\n" +
	"strategies\"2\n" +
	"\bStrategy\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04hostB:Z8github.com/erikeah/clavel/pkg/api/units/nixos/v1;nixosv1b\x06proto3"

var (
	file_clavel_units_nixos_v1_nixos_unit_proto_rawDescOnce sync.Once
	file_clavel_units_nixos_v1_nixos_unit_proto_rawDescData []byte
)

func file_clavel_units_nixos_v1_nixos_unit_proto_rawDescGZIP() []byte {
	file_clavel_units_nixos_v1_nixos_unit_proto_rawDescOnce.Do(func() {
		file_clavel_units_nixos_v1_nixos_unit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clavel_units_nixos_v1_nixos_unit_proto_rawDesc), len(file_clavel_units_nixos_v1_nixos_unit_proto_rawDesc)))
	})
	return file_clavel_units_nixos_v1_nixos_unit_proto_rawDescData
}

var file_clavel_units_nixos_v1_nixos_unit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_clavel_units_nixos_v1_nixos_unit_proto_goTypes = []any{
	(*NixosUnitSpec)(nil), // 0: clavel.units.nixos.v1.NixosUnitSpec
	(*Strategy)(nil),      // 1: clavel.units.nixos.v1.Strategy
}
var file_clavel_units_nixos_v1_nixos_unit_proto_depIdxs = []int32{
	1, // 0: clavel.units.nixos.v1.NixosUnitSpec.strategies:type_name -> clavel.units.nixos.v1.Strategy
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_clavel_units_nixos_v1_nixos_unit_proto_init() }
func file_clavel_units_nixos_v1_nixos_unit_proto_init() {
	if File_clavel_units_nixos_v1_nixos_unit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clavel_units_nixos_v1_nixos_unit_proto_rawDesc), len(file_clavel_units_nixos_v1_nixos_unit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clavel_units_nixos_v1_nixos_unit_proto_goTypes,
		DependencyIndexes: file_clavel_units_nixos_v1_nixos_unit_proto_depIdxs,
		MessageInfos:      file_clavel_units_nixos_v1_nixos_unit_proto_msgTypes,
	}.Build()
	File_clavel_units_nixos_v1_nixos_unit_proto = out.File
	file_clavel_units_nixos_v1_nixos_unit_proto_goTypes = nil
	file_clavel_units_nixos_v1_nixos_unit_proto_depIdxs = nil
}
