// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: clavel/agent/v1/agent.proto

package agent_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentSpecification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployments   []string               `protobuf:"bytes,1,rep,name=deployments,proto3" json:"deployments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSpecification) Reset() {
	*x = AgentSpecification{}
	mi := &file_clavel_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSpecification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSpecification) ProtoMessage() {}

func (x *AgentSpecification) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSpecification.ProtoReflect.Descriptor instead.
func (*AgentSpecification) Descriptor() ([]byte, []int) {
	return file_clavel_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentSpecification) GetDeployments() []string {
	if x != nil {
		return x.Deployments
	}
	return nil
}

type AgentServiceShowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentServiceShowRequest) Reset() {
	*x = AgentServiceShowRequest{}
	mi := &file_clavel_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentServiceShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentServiceShowRequest) ProtoMessage() {}

func (x *AgentServiceShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentServiceShowRequest.ProtoReflect.Descriptor instead.
func (*AgentServiceShowRequest) Descriptor() ([]byte, []int) {
	return file_clavel_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentServiceShowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AgentServiceShowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Spec          *AgentSpecification    `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentServiceShowResponse) Reset() {
	*x = AgentServiceShowResponse{}
	mi := &file_clavel_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentServiceShowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentServiceShowResponse) ProtoMessage() {}

func (x *AgentServiceShowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentServiceShowResponse.ProtoReflect.Descriptor instead.
func (*AgentServiceShowResponse) Descriptor() ([]byte, []int) {
	return file_clavel_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentServiceShowResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentServiceShowResponse) GetSpec() *AgentSpecification {
	if x != nil {
		return x.Spec
	}
	return nil
}

var File_clavel_agent_v1_agent_proto protoreflect.FileDescriptor

const file_clavel_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1bclavel/agent/v1/agent.proto\x12\x0fclavel.agent.v1\"6\n" +
	"\x12AgentSpecification\x12 \n" +
	"\vdeployments\x18\x01 \x03(\tR\vdeployments\"-\n" +
	"\x17AgentServiceShowRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"g\n" +
	"\x18AgentServiceShowResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\x04spec\x18\x02 \x01(\v2#.clavel.agent.v1.AgentSpecificationR\x04spec2m\n" +
	"\fAgentService\x12]\n" +
	"\x04Show\x12(.clavel.agent.v1.AgentServiceShowRequest\x1a).clavel.agent.v1.AgentServiceShowResponse\"\x00B4Z2github.com/erikeah/clavel/pkg/pb/agent/v1;agent_v1b\x06proto3"

var (
	file_clavel_agent_v1_agent_proto_rawDescOnce sync.Once
	file_clavel_agent_v1_agent_proto_rawDescData []byte
)

func file_clavel_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_clavel_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_clavel_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clavel_agent_v1_agent_proto_rawDesc), len(file_clavel_agent_v1_agent_proto_rawDesc)))
	})
	return file_clavel_agent_v1_agent_proto_rawDescData
}

var file_clavel_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_clavel_agent_v1_agent_proto_goTypes = []any{
	(*AgentSpecification)(nil),       // 0: clavel.agent.v1.AgentSpecification
	(*AgentServiceShowRequest)(nil),  // 1: clavel.agent.v1.AgentServiceShowRequest
	(*AgentServiceShowResponse)(nil), // 2: clavel.agent.v1.AgentServiceShowResponse
}
var file_clavel_agent_v1_agent_proto_depIdxs = []int32{
	0, // 0: clavel.agent.v1.AgentServiceShowResponse.spec:type_name -> clavel.agent.v1.AgentSpecification
	1, // 1: clavel.agent.v1.AgentService.Show:input_type -> clavel.agent.v1.AgentServiceShowRequest
	2, // 2: clavel.agent.v1.AgentService.Show:output_type -> clavel.agent.v1.AgentServiceShowResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_clavel_agent_v1_agent_proto_init() }
func file_clavel_agent_v1_agent_proto_init() {
	if File_clavel_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clavel_agent_v1_agent_proto_rawDesc), len(file_clavel_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clavel_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_clavel_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_clavel_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_clavel_agent_v1_agent_proto = out.File
	file_clavel_agent_v1_agent_proto_goTypes = nil
	file_clavel_agent_v1_agent_proto_depIdxs = nil
}
