// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: clavel/project/v1/project.proto

package projectv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/erikeah/clavel/pkg/pb/project/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProjectServiceName is the fully-qualified name of the ProjectService service.
	ProjectServiceName = "clavel.project.v1.ProjectService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProjectServiceShowProcedure is the fully-qualified name of the ProjectService's Show RPC.
	ProjectServiceShowProcedure = "/clavel.project.v1.ProjectService/Show"
	// ProjectServiceAddProcedure is the fully-qualified name of the ProjectService's Add RPC.
	ProjectServiceAddProcedure = "/clavel.project.v1.ProjectService/Add"
	// ProjectServiceListProcedure is the fully-qualified name of the ProjectService's List RPC.
	ProjectServiceListProcedure = "/clavel.project.v1.ProjectService/List"
)

// ProjectServiceClient is a client for the clavel.project.v1.ProjectService service.
type ProjectServiceClient interface {
	Show(context.Context, *connect.Request[v1.ProjectServiceShowRequest]) (*connect.Response[v1.ProjectServiceShowResponse], error)
	Add(context.Context, *connect.Request[v1.ProjectServiceAddRequest]) (*connect.Response[v1.ProjectServiceAddResponse], error)
	List(context.Context, *connect.Request[v1.ProjectServiceListRequest]) (*connect.Response[v1.ProjectServiceListResponse], error)
}

// NewProjectServiceClient constructs a client for the clavel.project.v1.ProjectService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProjectServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProjectServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	projectServiceMethods := v1.File_clavel_project_v1_project_proto.Services().ByName("ProjectService").Methods()
	return &projectServiceClient{
		show: connect.NewClient[v1.ProjectServiceShowRequest, v1.ProjectServiceShowResponse](
			httpClient,
			baseURL+ProjectServiceShowProcedure,
			connect.WithSchema(projectServiceMethods.ByName("Show")),
			connect.WithClientOptions(opts...),
		),
		add: connect.NewClient[v1.ProjectServiceAddRequest, v1.ProjectServiceAddResponse](
			httpClient,
			baseURL+ProjectServiceAddProcedure,
			connect.WithSchema(projectServiceMethods.ByName("Add")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.ProjectServiceListRequest, v1.ProjectServiceListResponse](
			httpClient,
			baseURL+ProjectServiceListProcedure,
			connect.WithSchema(projectServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
	}
}

// projectServiceClient implements ProjectServiceClient.
type projectServiceClient struct {
	show *connect.Client[v1.ProjectServiceShowRequest, v1.ProjectServiceShowResponse]
	add  *connect.Client[v1.ProjectServiceAddRequest, v1.ProjectServiceAddResponse]
	list *connect.Client[v1.ProjectServiceListRequest, v1.ProjectServiceListResponse]
}

// Show calls clavel.project.v1.ProjectService.Show.
func (c *projectServiceClient) Show(ctx context.Context, req *connect.Request[v1.ProjectServiceShowRequest]) (*connect.Response[v1.ProjectServiceShowResponse], error) {
	return c.show.CallUnary(ctx, req)
}

// Add calls clavel.project.v1.ProjectService.Add.
func (c *projectServiceClient) Add(ctx context.Context, req *connect.Request[v1.ProjectServiceAddRequest]) (*connect.Response[v1.ProjectServiceAddResponse], error) {
	return c.add.CallUnary(ctx, req)
}

// List calls clavel.project.v1.ProjectService.List.
func (c *projectServiceClient) List(ctx context.Context, req *connect.Request[v1.ProjectServiceListRequest]) (*connect.Response[v1.ProjectServiceListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// ProjectServiceHandler is an implementation of the clavel.project.v1.ProjectService service.
type ProjectServiceHandler interface {
	Show(context.Context, *connect.Request[v1.ProjectServiceShowRequest]) (*connect.Response[v1.ProjectServiceShowResponse], error)
	Add(context.Context, *connect.Request[v1.ProjectServiceAddRequest]) (*connect.Response[v1.ProjectServiceAddResponse], error)
	List(context.Context, *connect.Request[v1.ProjectServiceListRequest]) (*connect.Response[v1.ProjectServiceListResponse], error)
}

// NewProjectServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProjectServiceHandler(svc ProjectServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	projectServiceMethods := v1.File_clavel_project_v1_project_proto.Services().ByName("ProjectService").Methods()
	projectServiceShowHandler := connect.NewUnaryHandler(
		ProjectServiceShowProcedure,
		svc.Show,
		connect.WithSchema(projectServiceMethods.ByName("Show")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceAddHandler := connect.NewUnaryHandler(
		ProjectServiceAddProcedure,
		svc.Add,
		connect.WithSchema(projectServiceMethods.ByName("Add")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceListHandler := connect.NewUnaryHandler(
		ProjectServiceListProcedure,
		svc.List,
		connect.WithSchema(projectServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	return "/clavel.project.v1.ProjectService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProjectServiceShowProcedure:
			projectServiceShowHandler.ServeHTTP(w, r)
		case ProjectServiceAddProcedure:
			projectServiceAddHandler.ServeHTTP(w, r)
		case ProjectServiceListProcedure:
			projectServiceListHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProjectServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProjectServiceHandler struct{}

func (UnimplementedProjectServiceHandler) Show(context.Context, *connect.Request[v1.ProjectServiceShowRequest]) (*connect.Response[v1.ProjectServiceShowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clavel.project.v1.ProjectService.Show is not implemented"))
}

func (UnimplementedProjectServiceHandler) Add(context.Context, *connect.Request[v1.ProjectServiceAddRequest]) (*connect.Response[v1.ProjectServiceAddResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clavel.project.v1.ProjectService.Add is not implemented"))
}

func (UnimplementedProjectServiceHandler) List(context.Context, *connect.Request[v1.ProjectServiceListRequest]) (*connect.Response[v1.ProjectServiceListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clavel.project.v1.ProjectService.List is not implemented"))
}
