// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: clavel/project/v1/project.proto

package projectv1

import (
	v1 "github.com/erikeah/clavel/pkg/api/core/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectStatusPhase int32

const (
	ProjectStatusPhase_PROJECT_STATUS_PHASE_UNSPECIFIED ProjectStatusPhase = 0
	ProjectStatusPhase_PROJECT_STATUS_PHASE_READY       ProjectStatusPhase = 1
	ProjectStatusPhase_PROJECT_STATUS_PHASE_FAILED      ProjectStatusPhase = 2
)

// Enum value maps for ProjectStatusPhase.
var (
	ProjectStatusPhase_name = map[int32]string{
		0: "PROJECT_STATUS_PHASE_UNSPECIFIED",
		1: "PROJECT_STATUS_PHASE_READY",
		2: "PROJECT_STATUS_PHASE_FAILED",
	}
	ProjectStatusPhase_value = map[string]int32{
		"PROJECT_STATUS_PHASE_UNSPECIFIED": 0,
		"PROJECT_STATUS_PHASE_READY":       1,
		"PROJECT_STATUS_PHASE_FAILED":      2,
	}
)

func (x ProjectStatusPhase) Enum() *ProjectStatusPhase {
	p := new(ProjectStatusPhase)
	*p = x
	return p
}

func (x ProjectStatusPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectStatusPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_clavel_project_v1_project_proto_enumTypes[0].Descriptor()
}

func (ProjectStatusPhase) Type() protoreflect.EnumType {
	return &file_clavel_project_v1_project_proto_enumTypes[0]
}

func (x ProjectStatusPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProjectStatusPhase.Descriptor instead.
func (ProjectStatusPhase) EnumDescriptor() ([]byte, []int) {
	return file_clavel_project_v1_project_proto_rawDescGZIP(), []int{0}
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_clavel_project_v1_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_project_v1_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_clavel_project_v1_project_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProjectSpecification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flakeref      string                 `protobuf:"bytes,1,opt,name=flakeref,proto3" json:"flakeref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectSpecification) Reset() {
	*x = ProjectSpecification{}
	mi := &file_clavel_project_v1_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectSpecification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectSpecification) ProtoMessage() {}

func (x *ProjectSpecification) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_project_v1_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectSpecification.ProtoReflect.Descriptor instead.
func (*ProjectSpecification) Descriptor() ([]byte, []int) {
	return file_clavel_project_v1_project_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectSpecification) GetFlakeref() string {
	if x != nil {
		return x.Flakeref
	}
	return ""
}

type ProjectStatusSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	StorePath     string                 `protobuf:"bytes,2,opt,name=store_path,json=storePath,proto3" json:"store_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectStatusSource) Reset() {
	*x = ProjectStatusSource{}
	mi := &file_clavel_project_v1_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectStatusSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectStatusSource) ProtoMessage() {}

func (x *ProjectStatusSource) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_project_v1_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectStatusSource.ProtoReflect.Descriptor instead.
func (*ProjectStatusSource) Descriptor() ([]byte, []int) {
	return file_clavel_project_v1_project_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectStatusSource) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ProjectStatusSource) GetStorePath() string {
	if x != nil {
		return x.StorePath
	}
	return ""
}

type ProjectStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         ProjectStatusPhase     `protobuf:"varint,1,opt,name=phase,proto3,enum=clavel.project.v1.ProjectStatusPhase" json:"phase,omitempty"`
	Source        *ProjectStatusSource   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectStatus) Reset() {
	*x = ProjectStatus{}
	mi := &file_clavel_project_v1_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectStatus) ProtoMessage() {}

func (x *ProjectStatus) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_project_v1_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectStatus.ProtoReflect.Descriptor instead.
func (*ProjectStatus) Descriptor() ([]byte, []int) {
	return file_clavel_project_v1_project_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectStatus) GetPhase() ProjectStatusPhase {
	if x != nil {
		return x.Phase
	}
	return ProjectStatusPhase_PROJECT_STATUS_PHASE_UNSPECIFIED
}

func (x *ProjectStatus) GetSource() *ProjectStatusSource {
	if x != nil {
		return x.Source
	}
	return nil
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Spec          *ProjectSpecification  `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Metadata      *v1.Metadata           `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"` // ProjectStatus status = 4;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_clavel_project_v1_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_project_v1_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_clavel_project_v1_project_proto_rawDescGZIP(), []int{4}
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetSpec() *ProjectSpecification {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Project) GetMetadata() *v1.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ProjectServiceShowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceShowRequest) Reset() {
	*x = ProjectServiceShowRequest{}
	mi := &file_clavel_project_v1_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceShowRequest) ProtoMessage() {}

func (x *ProjectServiceShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_project_v1_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceShowRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceShowRequest) Descriptor() ([]byte, []int) {
	return file_clavel_project_v1_project_proto_rawDescGZIP(), []int{5}
}

func (x *ProjectServiceShowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProjectServiceShowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Project               `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceShowResponse) Reset() {
	*x = ProjectServiceShowResponse{}
	mi := &file_clavel_project_v1_project_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceShowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceShowResponse) ProtoMessage() {}

func (x *ProjectServiceShowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_project_v1_project_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceShowResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceShowResponse) Descriptor() ([]byte, []int) {
	return file_clavel_project_v1_project_proto_rawDescGZIP(), []int{6}
}

func (x *ProjectServiceShowResponse) GetData() *Project {
	if x != nil {
		return x.Data
	}
	return nil
}

type ProjectServiceCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Project               `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceCreateRequest) Reset() {
	*x = ProjectServiceCreateRequest{}
	mi := &file_clavel_project_v1_project_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceCreateRequest) ProtoMessage() {}

func (x *ProjectServiceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_project_v1_project_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceCreateRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceCreateRequest) Descriptor() ([]byte, []int) {
	return file_clavel_project_v1_project_proto_rawDescGZIP(), []int{7}
}

func (x *ProjectServiceCreateRequest) GetData() *Project {
	if x != nil {
		return x.Data
	}
	return nil
}

type ProjectServiceCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceCreateResponse) Reset() {
	*x = ProjectServiceCreateResponse{}
	mi := &file_clavel_project_v1_project_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceCreateResponse) ProtoMessage() {}

func (x *ProjectServiceCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_project_v1_project_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceCreateResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceCreateResponse) Descriptor() ([]byte, []int) {
	return file_clavel_project_v1_project_proto_rawDescGZIP(), []int{8}
}

type ProjectServiceListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceListRequest) Reset() {
	*x = ProjectServiceListRequest{}
	mi := &file_clavel_project_v1_project_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceListRequest) ProtoMessage() {}

func (x *ProjectServiceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_project_v1_project_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceListRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceListRequest) Descriptor() ([]byte, []int) {
	return file_clavel_project_v1_project_proto_rawDescGZIP(), []int{9}
}

type ProjectServiceListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Project             `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceListResponse) Reset() {
	*x = ProjectServiceListResponse{}
	mi := &file_clavel_project_v1_project_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceListResponse) ProtoMessage() {}

func (x *ProjectServiceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_project_v1_project_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceListResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceListResponse) Descriptor() ([]byte, []int) {
	return file_clavel_project_v1_project_proto_rawDescGZIP(), []int{10}
}

func (x *ProjectServiceListResponse) GetData() []*Project {
	if x != nil {
		return x.Data
	}
	return nil
}

type ProjectServiceDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceDeleteRequest) Reset() {
	*x = ProjectServiceDeleteRequest{}
	mi := &file_clavel_project_v1_project_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceDeleteRequest) ProtoMessage() {}

func (x *ProjectServiceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_project_v1_project_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceDeleteRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_clavel_project_v1_project_proto_rawDescGZIP(), []int{11}
}

func (x *ProjectServiceDeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProjectServiceDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceDeleteResponse) Reset() {
	*x = ProjectServiceDeleteResponse{}
	mi := &file_clavel_project_v1_project_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceDeleteResponse) ProtoMessage() {}

func (x *ProjectServiceDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_project_v1_project_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceDeleteResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceDeleteResponse) Descriptor() ([]byte, []int) {
	return file_clavel_project_v1_project_proto_rawDescGZIP(), []int{12}
}

type ProjectServiceUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data          *Project               `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceUpdateRequest) Reset() {
	*x = ProjectServiceUpdateRequest{}
	mi := &file_clavel_project_v1_project_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceUpdateRequest) ProtoMessage() {}

func (x *ProjectServiceUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_project_v1_project_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceUpdateRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceUpdateRequest) Descriptor() ([]byte, []int) {
	return file_clavel_project_v1_project_proto_rawDescGZIP(), []int{13}
}

func (x *ProjectServiceUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectServiceUpdateRequest) GetData() *Project {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ProjectServiceUpdateRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type ProjectServiceUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceUpdateResponse) Reset() {
	*x = ProjectServiceUpdateResponse{}
	mi := &file_clavel_project_v1_project_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceUpdateResponse) ProtoMessage() {}

func (x *ProjectServiceUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_project_v1_project_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceUpdateResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceUpdateResponse) Descriptor() ([]byte, []int) {
	return file_clavel_project_v1_project_proto_rawDescGZIP(), []int{14}
}

type ProjectServiceWatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceWatchRequest) Reset() {
	*x = ProjectServiceWatchRequest{}
	mi := &file_clavel_project_v1_project_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceWatchRequest) ProtoMessage() {}

func (x *ProjectServiceWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_project_v1_project_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceWatchRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceWatchRequest) Descriptor() ([]byte, []int) {
	return file_clavel_project_v1_project_proto_rawDescGZIP(), []int{15}
}

type ProjectServiceWatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Project               `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceWatchResponse) Reset() {
	*x = ProjectServiceWatchResponse{}
	mi := &file_clavel_project_v1_project_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceWatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceWatchResponse) ProtoMessage() {}

func (x *ProjectServiceWatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_project_v1_project_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceWatchResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceWatchResponse) Descriptor() ([]byte, []int) {
	return file_clavel_project_v1_project_proto_rawDescGZIP(), []int{16}
}

func (x *ProjectServiceWatchResponse) GetData() *Project {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ProjectServiceWatchResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_clavel_project_v1_project_proto protoreflect.FileDescriptor

const file_clavel_project_v1_project_proto_rawDesc = "" +
	"\n" +
	"\x1fclavel/project/v1/project.proto\x12\x11clavel.project.v1\x1a\x1dclavel/core/v1/metadata.proto\x1a google/protobuf/field_mask.proto\"!\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"2\n" +
	"\x14ProjectSpecification\x12\x1a\n" +
	"\bflakeref\x18\x01 \x01(\tR\bflakeref\"H\n" +
	"\x13ProjectStatusSource\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x1d\n" +
	"\n" +
	"store_path\x18\x02 \x01(\tR\tstorePath\"\x8c\x01\n" +
	"\rProjectStatus\x12;\n" +
	"\x05phase\x18\x01 \x01(\x0e2%.clavel.project.v1.ProjectStatusPhaseR\x05phase\x12>\n" +
	"\x06source\x18\x02 \x01(\v2&.clavel.project.v1.ProjectStatusSourceR\x06source\"\x90\x01\n" +
	"\aProject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\x04spec\x18\x02 \x01(\v2'.clavel.project.v1.ProjectSpecificationR\x04spec\x124\n" +
	"\bmetadata\x18\x03 \x01(\v2\x18.clavel.core.v1.MetadataR\bmetadata\"/\n" +
	"\x19ProjectServiceShowRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"L\n" +
	"\x1aProjectServiceShowResponse\x12.\n" +
	"\x04data\x18\x01 \x01(\v2\x1a.clavel.project.v1.ProjectR\x04data\"M\n" +
	"\x1bProjectServiceCreateRequest\x12.\n" +
	"\x04data\x18\x01 \x01(\v2\x1a.clavel.project.v1.ProjectR\x04data\"\x1e\n" +
	"\x1cProjectServiceCreateResponse\"\x1b\n" +
	"\x19ProjectServiceListRequest\"L\n" +
	"\x1aProjectServiceListResponse\x12.\n" +
	"\x04data\x18\x01 \x03(\v2\x1a.clavel.project.v1.ProjectR\x04data\"1\n" +
	"\x1bProjectServiceDeleteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1e\n" +
	"\x1cProjectServiceDeleteResponse\"\x9e\x01\n" +
	"\x1bProjectServiceUpdateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\x04data\x18\x02 \x01(\v2\x1a.clavel.project.v1.ProjectR\x04data\x12;\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\x1e\n" +
	"\x1cProjectServiceUpdateResponse\"\x1c\n" +
	"\x1aProjectServiceWatchRequest\"}\n" +
	"\x1bProjectServiceWatchResponse\x12.\n" +
	"\x04data\x18\x01 \x01(\v2\x1a.clavel.project.v1.ProjectR\x04data\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x18.clavel.project.v1.ErrorR\x05error*{\n" +
	"\x12ProjectStatusPhase\x12$\n" +
	" PROJECT_STATUS_PHASE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aPROJECT_STATUS_PHASE_READY\x10\x01\x12\x1f\n" +
	"\x1bPROJECT_STATUS_PHASE_FAILED\x10\x022\x91\x05\n" +
	"\x0eProjectService\x12e\n" +
	"\x04Show\x12,.clavel.project.v1.ProjectServiceShowRequest\x1a-.clavel.project.v1.ProjectServiceShowResponse\"\x00\x12e\n" +
	"\x04List\x12,.clavel.project.v1.ProjectServiceListRequest\x1a-.clavel.project.v1.ProjectServiceListResponse\"\x00\x12k\n" +
	"\x06Create\x12..clavel.project.v1.ProjectServiceCreateRequest\x1a/.clavel.project.v1.ProjectServiceCreateResponse\"\x00\x12k\n" +
	"\x06Update\x12..clavel.project.v1.ProjectServiceUpdateRequest\x1a/.clavel.project.v1.ProjectServiceUpdateResponse\"\x00\x12k\n" +
	"\x06Delete\x12..clavel.project.v1.ProjectServiceDeleteRequest\x1a/.clavel.project.v1.ProjectServiceDeleteResponse\"\x00\x12j\n" +
	"\x05Watch\x12-.clavel.project.v1.ProjectServiceWatchRequest\x1a..clavel.project.v1.ProjectServiceWatchResponse\"\x000\x01B8Z6github.com/erikeah/clavel/pkg/api/project/v1;projectv1b\x06proto3"

var (
	file_clavel_project_v1_project_proto_rawDescOnce sync.Once
	file_clavel_project_v1_project_proto_rawDescData []byte
)

func file_clavel_project_v1_project_proto_rawDescGZIP() []byte {
	file_clavel_project_v1_project_proto_rawDescOnce.Do(func() {
		file_clavel_project_v1_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clavel_project_v1_project_proto_rawDesc), len(file_clavel_project_v1_project_proto_rawDesc)))
	})
	return file_clavel_project_v1_project_proto_rawDescData
}

var file_clavel_project_v1_project_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_clavel_project_v1_project_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_clavel_project_v1_project_proto_goTypes = []any{
	(ProjectStatusPhase)(0),              // 0: clavel.project.v1.ProjectStatusPhase
	(*Error)(nil),                        // 1: clavel.project.v1.Error
	(*ProjectSpecification)(nil),         // 2: clavel.project.v1.ProjectSpecification
	(*ProjectStatusSource)(nil),          // 3: clavel.project.v1.ProjectStatusSource
	(*ProjectStatus)(nil),                // 4: clavel.project.v1.ProjectStatus
	(*Project)(nil),                      // 5: clavel.project.v1.Project
	(*ProjectServiceShowRequest)(nil),    // 6: clavel.project.v1.ProjectServiceShowRequest
	(*ProjectServiceShowResponse)(nil),   // 7: clavel.project.v1.ProjectServiceShowResponse
	(*ProjectServiceCreateRequest)(nil),  // 8: clavel.project.v1.ProjectServiceCreateRequest
	(*ProjectServiceCreateResponse)(nil), // 9: clavel.project.v1.ProjectServiceCreateResponse
	(*ProjectServiceListRequest)(nil),    // 10: clavel.project.v1.ProjectServiceListRequest
	(*ProjectServiceListResponse)(nil),   // 11: clavel.project.v1.ProjectServiceListResponse
	(*ProjectServiceDeleteRequest)(nil),  // 12: clavel.project.v1.ProjectServiceDeleteRequest
	(*ProjectServiceDeleteResponse)(nil), // 13: clavel.project.v1.ProjectServiceDeleteResponse
	(*ProjectServiceUpdateRequest)(nil),  // 14: clavel.project.v1.ProjectServiceUpdateRequest
	(*ProjectServiceUpdateResponse)(nil), // 15: clavel.project.v1.ProjectServiceUpdateResponse
	(*ProjectServiceWatchRequest)(nil),   // 16: clavel.project.v1.ProjectServiceWatchRequest
	(*ProjectServiceWatchResponse)(nil),  // 17: clavel.project.v1.ProjectServiceWatchResponse
	(*v1.Metadata)(nil),                  // 18: clavel.core.v1.Metadata
	(*fieldmaskpb.FieldMask)(nil),        // 19: google.protobuf.FieldMask
}
var file_clavel_project_v1_project_proto_depIdxs = []int32{
	0,  // 0: clavel.project.v1.ProjectStatus.phase:type_name -> clavel.project.v1.ProjectStatusPhase
	3,  // 1: clavel.project.v1.ProjectStatus.source:type_name -> clavel.project.v1.ProjectStatusSource
	2,  // 2: clavel.project.v1.Project.spec:type_name -> clavel.project.v1.ProjectSpecification
	18, // 3: clavel.project.v1.Project.metadata:type_name -> clavel.core.v1.Metadata
	5,  // 4: clavel.project.v1.ProjectServiceShowResponse.data:type_name -> clavel.project.v1.Project
	5,  // 5: clavel.project.v1.ProjectServiceCreateRequest.data:type_name -> clavel.project.v1.Project
	5,  // 6: clavel.project.v1.ProjectServiceListResponse.data:type_name -> clavel.project.v1.Project
	5,  // 7: clavel.project.v1.ProjectServiceUpdateRequest.data:type_name -> clavel.project.v1.Project
	19, // 8: clavel.project.v1.ProjectServiceUpdateRequest.update_mask:type_name -> google.protobuf.FieldMask
	5,  // 9: clavel.project.v1.ProjectServiceWatchResponse.data:type_name -> clavel.project.v1.Project
	1,  // 10: clavel.project.v1.ProjectServiceWatchResponse.error:type_name -> clavel.project.v1.Error
	6,  // 11: clavel.project.v1.ProjectService.Show:input_type -> clavel.project.v1.ProjectServiceShowRequest
	10, // 12: clavel.project.v1.ProjectService.List:input_type -> clavel.project.v1.ProjectServiceListRequest
	8,  // 13: clavel.project.v1.ProjectService.Create:input_type -> clavel.project.v1.ProjectServiceCreateRequest
	14, // 14: clavel.project.v1.ProjectService.Update:input_type -> clavel.project.v1.ProjectServiceUpdateRequest
	12, // 15: clavel.project.v1.ProjectService.Delete:input_type -> clavel.project.v1.ProjectServiceDeleteRequest
	16, // 16: clavel.project.v1.ProjectService.Watch:input_type -> clavel.project.v1.ProjectServiceWatchRequest
	7,  // 17: clavel.project.v1.ProjectService.Show:output_type -> clavel.project.v1.ProjectServiceShowResponse
	11, // 18: clavel.project.v1.ProjectService.List:output_type -> clavel.project.v1.ProjectServiceListResponse
	9,  // 19: clavel.project.v1.ProjectService.Create:output_type -> clavel.project.v1.ProjectServiceCreateResponse
	15, // 20: clavel.project.v1.ProjectService.Update:output_type -> clavel.project.v1.ProjectServiceUpdateResponse
	13, // 21: clavel.project.v1.ProjectService.Delete:output_type -> clavel.project.v1.ProjectServiceDeleteResponse
	17, // 22: clavel.project.v1.ProjectService.Watch:output_type -> clavel.project.v1.ProjectServiceWatchResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_clavel_project_v1_project_proto_init() }
func file_clavel_project_v1_project_proto_init() {
	if File_clavel_project_v1_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clavel_project_v1_project_proto_rawDesc), len(file_clavel_project_v1_project_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clavel_project_v1_project_proto_goTypes,
		DependencyIndexes: file_clavel_project_v1_project_proto_depIdxs,
		EnumInfos:         file_clavel_project_v1_project_proto_enumTypes,
		MessageInfos:      file_clavel_project_v1_project_proto_msgTypes,
	}.Build()
	File_clavel_project_v1_project_proto = out.File
	file_clavel_project_v1_project_proto_goTypes = nil
	file_clavel_project_v1_project_proto_depIdxs = nil
}
