// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: clavel/source/v1/source.proto

package sourcev1

import (
	v1 "github.com/erikeah/clavel/pkg/api/core/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SourceStatusPhase int32

const (
	SourceStatusPhase_SOURCE_STATUS_PHASE_UNSPECIFIED SourceStatusPhase = 0
	SourceStatusPhase_SOURCE_STATUS_PHASE_READY       SourceStatusPhase = 1
	SourceStatusPhase_SOURCE_STATUS_PHASE_FAILED      SourceStatusPhase = 2
)

// Enum value maps for SourceStatusPhase.
var (
	SourceStatusPhase_name = map[int32]string{
		0: "SOURCE_STATUS_PHASE_UNSPECIFIED",
		1: "SOURCE_STATUS_PHASE_READY",
		2: "SOURCE_STATUS_PHASE_FAILED",
	}
	SourceStatusPhase_value = map[string]int32{
		"SOURCE_STATUS_PHASE_UNSPECIFIED": 0,
		"SOURCE_STATUS_PHASE_READY":       1,
		"SOURCE_STATUS_PHASE_FAILED":      2,
	}
)

func (x SourceStatusPhase) Enum() *SourceStatusPhase {
	p := new(SourceStatusPhase)
	*p = x
	return p
}

func (x SourceStatusPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceStatusPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_clavel_source_v1_source_proto_enumTypes[0].Descriptor()
}

func (SourceStatusPhase) Type() protoreflect.EnumType {
	return &file_clavel_source_v1_source_proto_enumTypes[0]
}

func (x SourceStatusPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourceStatusPhase.Descriptor instead.
func (SourceStatusPhase) EnumDescriptor() ([]byte, []int) {
	return file_clavel_source_v1_source_proto_rawDescGZIP(), []int{0}
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_clavel_source_v1_source_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_source_v1_source_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_clavel_source_v1_source_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SourceSpecification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     string                 `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceSpecification) Reset() {
	*x = SourceSpecification{}
	mi := &file_clavel_source_v1_source_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceSpecification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceSpecification) ProtoMessage() {}

func (x *SourceSpecification) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_source_v1_source_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceSpecification.ProtoReflect.Descriptor instead.
func (*SourceSpecification) Descriptor() ([]byte, []int) {
	return file_clavel_source_v1_source_proto_rawDescGZIP(), []int{1}
}

func (x *SourceSpecification) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

type SourceStatusSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	StorePath     string                 `protobuf:"bytes,2,opt,name=store_path,json=storePath,proto3" json:"store_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceStatusSource) Reset() {
	*x = SourceStatusSource{}
	mi := &file_clavel_source_v1_source_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceStatusSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceStatusSource) ProtoMessage() {}

func (x *SourceStatusSource) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_source_v1_source_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceStatusSource.ProtoReflect.Descriptor instead.
func (*SourceStatusSource) Descriptor() ([]byte, []int) {
	return file_clavel_source_v1_source_proto_rawDescGZIP(), []int{2}
}

func (x *SourceStatusSource) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *SourceStatusSource) GetStorePath() string {
	if x != nil {
		return x.StorePath
	}
	return ""
}

type SourceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         SourceStatusPhase      `protobuf:"varint,1,opt,name=phase,proto3,enum=clavel.source.v1.SourceStatusPhase" json:"phase,omitempty"`
	Source        *SourceStatusSource    `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceStatus) Reset() {
	*x = SourceStatus{}
	mi := &file_clavel_source_v1_source_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceStatus) ProtoMessage() {}

func (x *SourceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_source_v1_source_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceStatus.ProtoReflect.Descriptor instead.
func (*SourceStatus) Descriptor() ([]byte, []int) {
	return file_clavel_source_v1_source_proto_rawDescGZIP(), []int{3}
}

func (x *SourceStatus) GetPhase() SourceStatusPhase {
	if x != nil {
		return x.Phase
	}
	return SourceStatusPhase_SOURCE_STATUS_PHASE_UNSPECIFIED
}

func (x *SourceStatus) GetSource() *SourceStatusSource {
	if x != nil {
		return x.Source
	}
	return nil
}

type Source struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Metadata *v1.Metadata           `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// SourceStatus status = 3;
	Spec          *SourceSpecification `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_clavel_source_v1_source_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_source_v1_source_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_clavel_source_v1_source_proto_rawDescGZIP(), []int{4}
}

func (x *Source) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Source) GetMetadata() *v1.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Source) GetSpec() *SourceSpecification {
	if x != nil {
		return x.Spec
	}
	return nil
}

type SourceServiceShowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceServiceShowRequest) Reset() {
	*x = SourceServiceShowRequest{}
	mi := &file_clavel_source_v1_source_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceServiceShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceServiceShowRequest) ProtoMessage() {}

func (x *SourceServiceShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_source_v1_source_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceServiceShowRequest.ProtoReflect.Descriptor instead.
func (*SourceServiceShowRequest) Descriptor() ([]byte, []int) {
	return file_clavel_source_v1_source_proto_rawDescGZIP(), []int{5}
}

func (x *SourceServiceShowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SourceServiceShowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Source                `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceServiceShowResponse) Reset() {
	*x = SourceServiceShowResponse{}
	mi := &file_clavel_source_v1_source_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceServiceShowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceServiceShowResponse) ProtoMessage() {}

func (x *SourceServiceShowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_source_v1_source_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceServiceShowResponse.ProtoReflect.Descriptor instead.
func (*SourceServiceShowResponse) Descriptor() ([]byte, []int) {
	return file_clavel_source_v1_source_proto_rawDescGZIP(), []int{6}
}

func (x *SourceServiceShowResponse) GetData() *Source {
	if x != nil {
		return x.Data
	}
	return nil
}

type SourceServiceCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Source                `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceServiceCreateRequest) Reset() {
	*x = SourceServiceCreateRequest{}
	mi := &file_clavel_source_v1_source_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceServiceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceServiceCreateRequest) ProtoMessage() {}

func (x *SourceServiceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_source_v1_source_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceServiceCreateRequest.ProtoReflect.Descriptor instead.
func (*SourceServiceCreateRequest) Descriptor() ([]byte, []int) {
	return file_clavel_source_v1_source_proto_rawDescGZIP(), []int{7}
}

func (x *SourceServiceCreateRequest) GetData() *Source {
	if x != nil {
		return x.Data
	}
	return nil
}

type SourceServiceCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceServiceCreateResponse) Reset() {
	*x = SourceServiceCreateResponse{}
	mi := &file_clavel_source_v1_source_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceServiceCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceServiceCreateResponse) ProtoMessage() {}

func (x *SourceServiceCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_source_v1_source_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceServiceCreateResponse.ProtoReflect.Descriptor instead.
func (*SourceServiceCreateResponse) Descriptor() ([]byte, []int) {
	return file_clavel_source_v1_source_proto_rawDescGZIP(), []int{8}
}

type SourceServiceListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceServiceListRequest) Reset() {
	*x = SourceServiceListRequest{}
	mi := &file_clavel_source_v1_source_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceServiceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceServiceListRequest) ProtoMessage() {}

func (x *SourceServiceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_source_v1_source_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceServiceListRequest.ProtoReflect.Descriptor instead.
func (*SourceServiceListRequest) Descriptor() ([]byte, []int) {
	return file_clavel_source_v1_source_proto_rawDescGZIP(), []int{9}
}

type SourceServiceListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Source              `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceServiceListResponse) Reset() {
	*x = SourceServiceListResponse{}
	mi := &file_clavel_source_v1_source_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceServiceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceServiceListResponse) ProtoMessage() {}

func (x *SourceServiceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_source_v1_source_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceServiceListResponse.ProtoReflect.Descriptor instead.
func (*SourceServiceListResponse) Descriptor() ([]byte, []int) {
	return file_clavel_source_v1_source_proto_rawDescGZIP(), []int{10}
}

func (x *SourceServiceListResponse) GetData() []*Source {
	if x != nil {
		return x.Data
	}
	return nil
}

type SourceServiceDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceServiceDeleteRequest) Reset() {
	*x = SourceServiceDeleteRequest{}
	mi := &file_clavel_source_v1_source_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceServiceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceServiceDeleteRequest) ProtoMessage() {}

func (x *SourceServiceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_source_v1_source_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceServiceDeleteRequest.ProtoReflect.Descriptor instead.
func (*SourceServiceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_clavel_source_v1_source_proto_rawDescGZIP(), []int{11}
}

func (x *SourceServiceDeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SourceServiceDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceServiceDeleteResponse) Reset() {
	*x = SourceServiceDeleteResponse{}
	mi := &file_clavel_source_v1_source_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceServiceDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceServiceDeleteResponse) ProtoMessage() {}

func (x *SourceServiceDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_source_v1_source_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceServiceDeleteResponse.ProtoReflect.Descriptor instead.
func (*SourceServiceDeleteResponse) Descriptor() ([]byte, []int) {
	return file_clavel_source_v1_source_proto_rawDescGZIP(), []int{12}
}

type SourceServiceUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data          *Source                `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceServiceUpdateRequest) Reset() {
	*x = SourceServiceUpdateRequest{}
	mi := &file_clavel_source_v1_source_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceServiceUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceServiceUpdateRequest) ProtoMessage() {}

func (x *SourceServiceUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_source_v1_source_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceServiceUpdateRequest.ProtoReflect.Descriptor instead.
func (*SourceServiceUpdateRequest) Descriptor() ([]byte, []int) {
	return file_clavel_source_v1_source_proto_rawDescGZIP(), []int{13}
}

func (x *SourceServiceUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SourceServiceUpdateRequest) GetData() *Source {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SourceServiceUpdateRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type SourceServiceUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceServiceUpdateResponse) Reset() {
	*x = SourceServiceUpdateResponse{}
	mi := &file_clavel_source_v1_source_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceServiceUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceServiceUpdateResponse) ProtoMessage() {}

func (x *SourceServiceUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_source_v1_source_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceServiceUpdateResponse.ProtoReflect.Descriptor instead.
func (*SourceServiceUpdateResponse) Descriptor() ([]byte, []int) {
	return file_clavel_source_v1_source_proto_rawDescGZIP(), []int{14}
}

type SourceServiceWatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          bool                   `protobuf:"varint,1,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceServiceWatchRequest) Reset() {
	*x = SourceServiceWatchRequest{}
	mi := &file_clavel_source_v1_source_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceServiceWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceServiceWatchRequest) ProtoMessage() {}

func (x *SourceServiceWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_source_v1_source_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceServiceWatchRequest.ProtoReflect.Descriptor instead.
func (*SourceServiceWatchRequest) Descriptor() ([]byte, []int) {
	return file_clavel_source_v1_source_proto_rawDescGZIP(), []int{15}
}

func (x *SourceServiceWatchRequest) GetList() bool {
	if x != nil {
		return x.List
	}
	return false
}

type SourceServiceWatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Source                `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceServiceWatchResponse) Reset() {
	*x = SourceServiceWatchResponse{}
	mi := &file_clavel_source_v1_source_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceServiceWatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceServiceWatchResponse) ProtoMessage() {}

func (x *SourceServiceWatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_source_v1_source_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceServiceWatchResponse.ProtoReflect.Descriptor instead.
func (*SourceServiceWatchResponse) Descriptor() ([]byte, []int) {
	return file_clavel_source_v1_source_proto_rawDescGZIP(), []int{16}
}

func (x *SourceServiceWatchResponse) GetData() *Source {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SourceServiceWatchResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_clavel_source_v1_source_proto protoreflect.FileDescriptor

const file_clavel_source_v1_source_proto_rawDesc = "" +
	"\n" +
	"\x1dclavel/source/v1/source.proto\x12\x10clavel.source.v1\x1a\x1dclavel/core/v1/metadata.proto\x1a google/protobuf/field_mask.proto\"!\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"3\n" +
	"\x13SourceSpecification\x12\x1c\n" +
	"\treference\x18\x01 \x01(\tR\treference\"G\n" +
	"\x12SourceStatusSource\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x1d\n" +
	"\n" +
	"store_path\x18\x02 \x01(\tR\tstorePath\"\x87\x01\n" +
	"\fSourceStatus\x129\n" +
	"\x05phase\x18\x01 \x01(\x0e2#.clavel.source.v1.SourceStatusPhaseR\x05phase\x12<\n" +
	"\x06source\x18\x02 \x01(\v2$.clavel.source.v1.SourceStatusSourceR\x06source\"\x8d\x01\n" +
	"\x06Source\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\bmetadata\x18\x02 \x01(\v2\x18.clavel.core.v1.MetadataR\bmetadata\x129\n" +
	"\x04spec\x18\x04 \x01(\v2%.clavel.source.v1.SourceSpecificationR\x04spec\".\n" +
	"\x18SourceServiceShowRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"I\n" +
	"\x19SourceServiceShowResponse\x12,\n" +
	"\x04data\x18\x01 \x01(\v2\x18.clavel.source.v1.SourceR\x04data\"J\n" +
	"\x1aSourceServiceCreateRequest\x12,\n" +
	"\x04data\x18\x01 \x01(\v2\x18.clavel.source.v1.SourceR\x04data\"\x1d\n" +
	"\x1bSourceServiceCreateResponse\"\x1a\n" +
	"\x18SourceServiceListRequest\"I\n" +
	"\x19SourceServiceListResponse\x12,\n" +
	"\x04data\x18\x01 \x03(\v2\x18.clavel.source.v1.SourceR\x04data\"0\n" +
	"\x1aSourceServiceDeleteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1d\n" +
	"\x1bSourceServiceDeleteResponse\"\x9b\x01\n" +
	"\x1aSourceServiceUpdateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x04data\x18\x02 \x01(\v2\x18.clavel.source.v1.SourceR\x04data\x12;\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\x1d\n" +
	"\x1bSourceServiceUpdateResponse\"/\n" +
	"\x19SourceServiceWatchRequest\x12\x12\n" +
	"\x04list\x18\x01 \x01(\bR\x04list\"y\n" +
	"\x1aSourceServiceWatchResponse\x12,\n" +
	"\x04data\x18\x01 \x01(\v2\x18.clavel.source.v1.SourceR\x04data\x12-\n" +
	"\x05error\x18\x02 \x01(\v2\x17.clavel.source.v1.ErrorR\x05error*w\n" +
	"\x11SourceStatusPhase\x12#\n" +
	"\x1fSOURCE_STATUS_PHASE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19SOURCE_STATUS_PHASE_READY\x10\x01\x12\x1e\n" +
	"\x1aSOURCE_STATUS_PHASE_FAILED\x10\x022\xf8\x04\n" +
	"\rSourceService\x12a\n" +
	"\x04Show\x12*.clavel.source.v1.SourceServiceShowRequest\x1a+.clavel.source.v1.SourceServiceShowResponse\"\x00\x12a\n" +
	"\x04List\x12*.clavel.source.v1.SourceServiceListRequest\x1a+.clavel.source.v1.SourceServiceListResponse\"\x00\x12g\n" +
	"\x06Create\x12,.clavel.source.v1.SourceServiceCreateRequest\x1a-.clavel.source.v1.SourceServiceCreateResponse\"\x00\x12g\n" +
	"\x06Update\x12,.clavel.source.v1.SourceServiceUpdateRequest\x1a-.clavel.source.v1.SourceServiceUpdateResponse\"\x00\x12g\n" +
	"\x06Delete\x12,.clavel.source.v1.SourceServiceDeleteRequest\x1a-.clavel.source.v1.SourceServiceDeleteResponse\"\x00\x12f\n" +
	"\x05Watch\x12+.clavel.source.v1.SourceServiceWatchRequest\x1a,.clavel.source.v1.SourceServiceWatchResponse\"\x000\x01B6Z4github.com/erikeah/clavel/pkg/api/source/v1;sourcev1b\x06proto3"

var (
	file_clavel_source_v1_source_proto_rawDescOnce sync.Once
	file_clavel_source_v1_source_proto_rawDescData []byte
)

func file_clavel_source_v1_source_proto_rawDescGZIP() []byte {
	file_clavel_source_v1_source_proto_rawDescOnce.Do(func() {
		file_clavel_source_v1_source_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clavel_source_v1_source_proto_rawDesc), len(file_clavel_source_v1_source_proto_rawDesc)))
	})
	return file_clavel_source_v1_source_proto_rawDescData
}

var file_clavel_source_v1_source_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_clavel_source_v1_source_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_clavel_source_v1_source_proto_goTypes = []any{
	(SourceStatusPhase)(0),              // 0: clavel.source.v1.SourceStatusPhase
	(*Error)(nil),                       // 1: clavel.source.v1.Error
	(*SourceSpecification)(nil),         // 2: clavel.source.v1.SourceSpecification
	(*SourceStatusSource)(nil),          // 3: clavel.source.v1.SourceStatusSource
	(*SourceStatus)(nil),                // 4: clavel.source.v1.SourceStatus
	(*Source)(nil),                      // 5: clavel.source.v1.Source
	(*SourceServiceShowRequest)(nil),    // 6: clavel.source.v1.SourceServiceShowRequest
	(*SourceServiceShowResponse)(nil),   // 7: clavel.source.v1.SourceServiceShowResponse
	(*SourceServiceCreateRequest)(nil),  // 8: clavel.source.v1.SourceServiceCreateRequest
	(*SourceServiceCreateResponse)(nil), // 9: clavel.source.v1.SourceServiceCreateResponse
	(*SourceServiceListRequest)(nil),    // 10: clavel.source.v1.SourceServiceListRequest
	(*SourceServiceListResponse)(nil),   // 11: clavel.source.v1.SourceServiceListResponse
	(*SourceServiceDeleteRequest)(nil),  // 12: clavel.source.v1.SourceServiceDeleteRequest
	(*SourceServiceDeleteResponse)(nil), // 13: clavel.source.v1.SourceServiceDeleteResponse
	(*SourceServiceUpdateRequest)(nil),  // 14: clavel.source.v1.SourceServiceUpdateRequest
	(*SourceServiceUpdateResponse)(nil), // 15: clavel.source.v1.SourceServiceUpdateResponse
	(*SourceServiceWatchRequest)(nil),   // 16: clavel.source.v1.SourceServiceWatchRequest
	(*SourceServiceWatchResponse)(nil),  // 17: clavel.source.v1.SourceServiceWatchResponse
	(*v1.Metadata)(nil),                 // 18: clavel.core.v1.Metadata
	(*fieldmaskpb.FieldMask)(nil),       // 19: google.protobuf.FieldMask
}
var file_clavel_source_v1_source_proto_depIdxs = []int32{
	0,  // 0: clavel.source.v1.SourceStatus.phase:type_name -> clavel.source.v1.SourceStatusPhase
	3,  // 1: clavel.source.v1.SourceStatus.source:type_name -> clavel.source.v1.SourceStatusSource
	18, // 2: clavel.source.v1.Source.metadata:type_name -> clavel.core.v1.Metadata
	2,  // 3: clavel.source.v1.Source.spec:type_name -> clavel.source.v1.SourceSpecification
	5,  // 4: clavel.source.v1.SourceServiceShowResponse.data:type_name -> clavel.source.v1.Source
	5,  // 5: clavel.source.v1.SourceServiceCreateRequest.data:type_name -> clavel.source.v1.Source
	5,  // 6: clavel.source.v1.SourceServiceListResponse.data:type_name -> clavel.source.v1.Source
	5,  // 7: clavel.source.v1.SourceServiceUpdateRequest.data:type_name -> clavel.source.v1.Source
	19, // 8: clavel.source.v1.SourceServiceUpdateRequest.update_mask:type_name -> google.protobuf.FieldMask
	5,  // 9: clavel.source.v1.SourceServiceWatchResponse.data:type_name -> clavel.source.v1.Source
	1,  // 10: clavel.source.v1.SourceServiceWatchResponse.error:type_name -> clavel.source.v1.Error
	6,  // 11: clavel.source.v1.SourceService.Show:input_type -> clavel.source.v1.SourceServiceShowRequest
	10, // 12: clavel.source.v1.SourceService.List:input_type -> clavel.source.v1.SourceServiceListRequest
	8,  // 13: clavel.source.v1.SourceService.Create:input_type -> clavel.source.v1.SourceServiceCreateRequest
	14, // 14: clavel.source.v1.SourceService.Update:input_type -> clavel.source.v1.SourceServiceUpdateRequest
	12, // 15: clavel.source.v1.SourceService.Delete:input_type -> clavel.source.v1.SourceServiceDeleteRequest
	16, // 16: clavel.source.v1.SourceService.Watch:input_type -> clavel.source.v1.SourceServiceWatchRequest
	7,  // 17: clavel.source.v1.SourceService.Show:output_type -> clavel.source.v1.SourceServiceShowResponse
	11, // 18: clavel.source.v1.SourceService.List:output_type -> clavel.source.v1.SourceServiceListResponse
	9,  // 19: clavel.source.v1.SourceService.Create:output_type -> clavel.source.v1.SourceServiceCreateResponse
	15, // 20: clavel.source.v1.SourceService.Update:output_type -> clavel.source.v1.SourceServiceUpdateResponse
	13, // 21: clavel.source.v1.SourceService.Delete:output_type -> clavel.source.v1.SourceServiceDeleteResponse
	17, // 22: clavel.source.v1.SourceService.Watch:output_type -> clavel.source.v1.SourceServiceWatchResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_clavel_source_v1_source_proto_init() }
func file_clavel_source_v1_source_proto_init() {
	if File_clavel_source_v1_source_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clavel_source_v1_source_proto_rawDesc), len(file_clavel_source_v1_source_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clavel_source_v1_source_proto_goTypes,
		DependencyIndexes: file_clavel_source_v1_source_proto_depIdxs,
		EnumInfos:         file_clavel_source_v1_source_proto_enumTypes,
		MessageInfos:      file_clavel_source_v1_source_proto_msgTypes,
	}.Build()
	File_clavel_source_v1_source_proto = out.File
	file_clavel_source_v1_source_proto_goTypes = nil
	file_clavel_source_v1_source_proto_depIdxs = nil
}
