// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: clavel/deployment/v1/deployment.proto

package deployment_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeploymentServiceShowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentServiceShowRequest) Reset() {
	*x = DeploymentServiceShowRequest{}
	mi := &file_clavel_deployment_v1_deployment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentServiceShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentServiceShowRequest) ProtoMessage() {}

func (x *DeploymentServiceShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_deployment_v1_deployment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentServiceShowRequest.ProtoReflect.Descriptor instead.
func (*DeploymentServiceShowRequest) Descriptor() ([]byte, []int) {
	return file_clavel_deployment_v1_deployment_proto_rawDescGZIP(), []int{0}
}

func (x *DeploymentServiceShowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeploymentServiceShowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentServiceShowResponse) Reset() {
	*x = DeploymentServiceShowResponse{}
	mi := &file_clavel_deployment_v1_deployment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentServiceShowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentServiceShowResponse) ProtoMessage() {}

func (x *DeploymentServiceShowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavel_deployment_v1_deployment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentServiceShowResponse.ProtoReflect.Descriptor instead.
func (*DeploymentServiceShowResponse) Descriptor() ([]byte, []int) {
	return file_clavel_deployment_v1_deployment_proto_rawDescGZIP(), []int{1}
}

func (x *DeploymentServiceShowResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_clavel_deployment_v1_deployment_proto protoreflect.FileDescriptor

const file_clavel_deployment_v1_deployment_proto_rawDesc = "" +
	"\n" +
	"%clavel/deployment/v1/deployment.proto\x12\x14clavel.deployment.v1\"2\n" +
	"\x1cDeploymentServiceShowRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"3\n" +
	"\x1dDeploymentServiceShowResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\x86\x01\n" +
	"\x11DeploymentService\x12q\n" +
	"\x04Show\x122.clavel.deployment.v1.DeploymentServiceShowRequest\x1a3.clavel.deployment.v1.DeploymentServiceShowResponse\"\x00B>Z<github.com/erikeah/clavel/pkg/pb/deployment/v1;deployment_v1b\x06proto3"

var (
	file_clavel_deployment_v1_deployment_proto_rawDescOnce sync.Once
	file_clavel_deployment_v1_deployment_proto_rawDescData []byte
)

func file_clavel_deployment_v1_deployment_proto_rawDescGZIP() []byte {
	file_clavel_deployment_v1_deployment_proto_rawDescOnce.Do(func() {
		file_clavel_deployment_v1_deployment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clavel_deployment_v1_deployment_proto_rawDesc), len(file_clavel_deployment_v1_deployment_proto_rawDesc)))
	})
	return file_clavel_deployment_v1_deployment_proto_rawDescData
}

var file_clavel_deployment_v1_deployment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_clavel_deployment_v1_deployment_proto_goTypes = []any{
	(*DeploymentServiceShowRequest)(nil),  // 0: clavel.deployment.v1.DeploymentServiceShowRequest
	(*DeploymentServiceShowResponse)(nil), // 1: clavel.deployment.v1.DeploymentServiceShowResponse
}
var file_clavel_deployment_v1_deployment_proto_depIdxs = []int32{
	0, // 0: clavel.deployment.v1.DeploymentService.Show:input_type -> clavel.deployment.v1.DeploymentServiceShowRequest
	1, // 1: clavel.deployment.v1.DeploymentService.Show:output_type -> clavel.deployment.v1.DeploymentServiceShowResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clavel_deployment_v1_deployment_proto_init() }
func file_clavel_deployment_v1_deployment_proto_init() {
	if File_clavel_deployment_v1_deployment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clavel_deployment_v1_deployment_proto_rawDesc), len(file_clavel_deployment_v1_deployment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clavel_deployment_v1_deployment_proto_goTypes,
		DependencyIndexes: file_clavel_deployment_v1_deployment_proto_depIdxs,
		MessageInfos:      file_clavel_deployment_v1_deployment_proto_msgTypes,
	}.Build()
	File_clavel_deployment_v1_deployment_proto = out.File
	file_clavel_deployment_v1_deployment_proto_goTypes = nil
	file_clavel_deployment_v1_deployment_proto_depIdxs = nil
}
