// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: clavel/core/v1/artifact.proto

package corev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/erikeah/clavel/pkg/api/core/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ArtifactServiceName is the fully-qualified name of the ArtifactService service.
	ArtifactServiceName = "clavel.core.v1.ArtifactService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ArtifactServiceShowProcedure is the fully-qualified name of the ArtifactService's Show RPC.
	ArtifactServiceShowProcedure = "/clavel.core.v1.ArtifactService/Show"
	// ArtifactServiceListProcedure is the fully-qualified name of the ArtifactService's List RPC.
	ArtifactServiceListProcedure = "/clavel.core.v1.ArtifactService/List"
	// ArtifactServiceCreateProcedure is the fully-qualified name of the ArtifactService's Create RPC.
	ArtifactServiceCreateProcedure = "/clavel.core.v1.ArtifactService/Create"
	// ArtifactServiceUpdateProcedure is the fully-qualified name of the ArtifactService's Update RPC.
	ArtifactServiceUpdateProcedure = "/clavel.core.v1.ArtifactService/Update"
	// ArtifactServiceDeleteProcedure is the fully-qualified name of the ArtifactService's Delete RPC.
	ArtifactServiceDeleteProcedure = "/clavel.core.v1.ArtifactService/Delete"
	// ArtifactServiceWatchProcedure is the fully-qualified name of the ArtifactService's Watch RPC.
	ArtifactServiceWatchProcedure = "/clavel.core.v1.ArtifactService/Watch"
)

// ArtifactServiceClient is a client for the clavel.core.v1.ArtifactService service.
type ArtifactServiceClient interface {
	Show(context.Context, *connect.Request[v1.ArtifactServiceShowRequest]) (*connect.Response[v1.ArtifactServiceShowResponse], error)
	List(context.Context, *connect.Request[v1.ArtifactServiceListRequest]) (*connect.Response[v1.ArtifactServiceListResponse], error)
	Create(context.Context, *connect.Request[v1.ArtifactServiceCreateRequest]) (*connect.Response[v1.ArtifactServiceCreateResponse], error)
	Update(context.Context, *connect.Request[v1.ArtifactServiceUpdateRequest]) (*connect.Response[v1.ArtifactServiceUpdateResponse], error)
	Delete(context.Context, *connect.Request[v1.ArtifactServiceDeleteRequest]) (*connect.Response[v1.ArtifactServiceDeleteResponse], error)
	Watch(context.Context, *connect.Request[v1.ArtifactServiceWatchRequest]) (*connect.ServerStreamForClient[v1.ArtifactServiceWatchResponse], error)
}

// NewArtifactServiceClient constructs a client for the clavel.core.v1.ArtifactService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewArtifactServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ArtifactServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	artifactServiceMethods := v1.File_clavel_core_v1_artifact_proto.Services().ByName("ArtifactService").Methods()
	return &artifactServiceClient{
		show: connect.NewClient[v1.ArtifactServiceShowRequest, v1.ArtifactServiceShowResponse](
			httpClient,
			baseURL+ArtifactServiceShowProcedure,
			connect.WithSchema(artifactServiceMethods.ByName("Show")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.ArtifactServiceListRequest, v1.ArtifactServiceListResponse](
			httpClient,
			baseURL+ArtifactServiceListProcedure,
			connect.WithSchema(artifactServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		create: connect.NewClient[v1.ArtifactServiceCreateRequest, v1.ArtifactServiceCreateResponse](
			httpClient,
			baseURL+ArtifactServiceCreateProcedure,
			connect.WithSchema(artifactServiceMethods.ByName("Create")),
			connect.WithClientOptions(opts...),
		),
		update: connect.NewClient[v1.ArtifactServiceUpdateRequest, v1.ArtifactServiceUpdateResponse](
			httpClient,
			baseURL+ArtifactServiceUpdateProcedure,
			connect.WithSchema(artifactServiceMethods.ByName("Update")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1.ArtifactServiceDeleteRequest, v1.ArtifactServiceDeleteResponse](
			httpClient,
			baseURL+ArtifactServiceDeleteProcedure,
			connect.WithSchema(artifactServiceMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		watch: connect.NewClient[v1.ArtifactServiceWatchRequest, v1.ArtifactServiceWatchResponse](
			httpClient,
			baseURL+ArtifactServiceWatchProcedure,
			connect.WithSchema(artifactServiceMethods.ByName("Watch")),
			connect.WithClientOptions(opts...),
		),
	}
}

// artifactServiceClient implements ArtifactServiceClient.
type artifactServiceClient struct {
	show   *connect.Client[v1.ArtifactServiceShowRequest, v1.ArtifactServiceShowResponse]
	list   *connect.Client[v1.ArtifactServiceListRequest, v1.ArtifactServiceListResponse]
	create *connect.Client[v1.ArtifactServiceCreateRequest, v1.ArtifactServiceCreateResponse]
	update *connect.Client[v1.ArtifactServiceUpdateRequest, v1.ArtifactServiceUpdateResponse]
	delete *connect.Client[v1.ArtifactServiceDeleteRequest, v1.ArtifactServiceDeleteResponse]
	watch  *connect.Client[v1.ArtifactServiceWatchRequest, v1.ArtifactServiceWatchResponse]
}

// Show calls clavel.core.v1.ArtifactService.Show.
func (c *artifactServiceClient) Show(ctx context.Context, req *connect.Request[v1.ArtifactServiceShowRequest]) (*connect.Response[v1.ArtifactServiceShowResponse], error) {
	return c.show.CallUnary(ctx, req)
}

// List calls clavel.core.v1.ArtifactService.List.
func (c *artifactServiceClient) List(ctx context.Context, req *connect.Request[v1.ArtifactServiceListRequest]) (*connect.Response[v1.ArtifactServiceListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Create calls clavel.core.v1.ArtifactService.Create.
func (c *artifactServiceClient) Create(ctx context.Context, req *connect.Request[v1.ArtifactServiceCreateRequest]) (*connect.Response[v1.ArtifactServiceCreateResponse], error) {
	return c.create.CallUnary(ctx, req)
}

// Update calls clavel.core.v1.ArtifactService.Update.
func (c *artifactServiceClient) Update(ctx context.Context, req *connect.Request[v1.ArtifactServiceUpdateRequest]) (*connect.Response[v1.ArtifactServiceUpdateResponse], error) {
	return c.update.CallUnary(ctx, req)
}

// Delete calls clavel.core.v1.ArtifactService.Delete.
func (c *artifactServiceClient) Delete(ctx context.Context, req *connect.Request[v1.ArtifactServiceDeleteRequest]) (*connect.Response[v1.ArtifactServiceDeleteResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// Watch calls clavel.core.v1.ArtifactService.Watch.
func (c *artifactServiceClient) Watch(ctx context.Context, req *connect.Request[v1.ArtifactServiceWatchRequest]) (*connect.ServerStreamForClient[v1.ArtifactServiceWatchResponse], error) {
	return c.watch.CallServerStream(ctx, req)
}

// ArtifactServiceHandler is an implementation of the clavel.core.v1.ArtifactService service.
type ArtifactServiceHandler interface {
	Show(context.Context, *connect.Request[v1.ArtifactServiceShowRequest]) (*connect.Response[v1.ArtifactServiceShowResponse], error)
	List(context.Context, *connect.Request[v1.ArtifactServiceListRequest]) (*connect.Response[v1.ArtifactServiceListResponse], error)
	Create(context.Context, *connect.Request[v1.ArtifactServiceCreateRequest]) (*connect.Response[v1.ArtifactServiceCreateResponse], error)
	Update(context.Context, *connect.Request[v1.ArtifactServiceUpdateRequest]) (*connect.Response[v1.ArtifactServiceUpdateResponse], error)
	Delete(context.Context, *connect.Request[v1.ArtifactServiceDeleteRequest]) (*connect.Response[v1.ArtifactServiceDeleteResponse], error)
	Watch(context.Context, *connect.Request[v1.ArtifactServiceWatchRequest], *connect.ServerStream[v1.ArtifactServiceWatchResponse]) error
}

// NewArtifactServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewArtifactServiceHandler(svc ArtifactServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	artifactServiceMethods := v1.File_clavel_core_v1_artifact_proto.Services().ByName("ArtifactService").Methods()
	artifactServiceShowHandler := connect.NewUnaryHandler(
		ArtifactServiceShowProcedure,
		svc.Show,
		connect.WithSchema(artifactServiceMethods.ByName("Show")),
		connect.WithHandlerOptions(opts...),
	)
	artifactServiceListHandler := connect.NewUnaryHandler(
		ArtifactServiceListProcedure,
		svc.List,
		connect.WithSchema(artifactServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	artifactServiceCreateHandler := connect.NewUnaryHandler(
		ArtifactServiceCreateProcedure,
		svc.Create,
		connect.WithSchema(artifactServiceMethods.ByName("Create")),
		connect.WithHandlerOptions(opts...),
	)
	artifactServiceUpdateHandler := connect.NewUnaryHandler(
		ArtifactServiceUpdateProcedure,
		svc.Update,
		connect.WithSchema(artifactServiceMethods.ByName("Update")),
		connect.WithHandlerOptions(opts...),
	)
	artifactServiceDeleteHandler := connect.NewUnaryHandler(
		ArtifactServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(artifactServiceMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	artifactServiceWatchHandler := connect.NewServerStreamHandler(
		ArtifactServiceWatchProcedure,
		svc.Watch,
		connect.WithSchema(artifactServiceMethods.ByName("Watch")),
		connect.WithHandlerOptions(opts...),
	)
	return "/clavel.core.v1.ArtifactService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ArtifactServiceShowProcedure:
			artifactServiceShowHandler.ServeHTTP(w, r)
		case ArtifactServiceListProcedure:
			artifactServiceListHandler.ServeHTTP(w, r)
		case ArtifactServiceCreateProcedure:
			artifactServiceCreateHandler.ServeHTTP(w, r)
		case ArtifactServiceUpdateProcedure:
			artifactServiceUpdateHandler.ServeHTTP(w, r)
		case ArtifactServiceDeleteProcedure:
			artifactServiceDeleteHandler.ServeHTTP(w, r)
		case ArtifactServiceWatchProcedure:
			artifactServiceWatchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedArtifactServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedArtifactServiceHandler struct{}

func (UnimplementedArtifactServiceHandler) Show(context.Context, *connect.Request[v1.ArtifactServiceShowRequest]) (*connect.Response[v1.ArtifactServiceShowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clavel.core.v1.ArtifactService.Show is not implemented"))
}

func (UnimplementedArtifactServiceHandler) List(context.Context, *connect.Request[v1.ArtifactServiceListRequest]) (*connect.Response[v1.ArtifactServiceListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clavel.core.v1.ArtifactService.List is not implemented"))
}

func (UnimplementedArtifactServiceHandler) Create(context.Context, *connect.Request[v1.ArtifactServiceCreateRequest]) (*connect.Response[v1.ArtifactServiceCreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clavel.core.v1.ArtifactService.Create is not implemented"))
}

func (UnimplementedArtifactServiceHandler) Update(context.Context, *connect.Request[v1.ArtifactServiceUpdateRequest]) (*connect.Response[v1.ArtifactServiceUpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clavel.core.v1.ArtifactService.Update is not implemented"))
}

func (UnimplementedArtifactServiceHandler) Delete(context.Context, *connect.Request[v1.ArtifactServiceDeleteRequest]) (*connect.Response[v1.ArtifactServiceDeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clavel.core.v1.ArtifactService.Delete is not implemented"))
}

func (UnimplementedArtifactServiceHandler) Watch(context.Context, *connect.Request[v1.ArtifactServiceWatchRequest], *connect.ServerStream[v1.ArtifactServiceWatchResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("clavel.core.v1.ArtifactService.Watch is not implemented"))
}
