// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: clavel/core/v1/custom_resource.proto

package corev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/erikeah/clavel/pkg/api/core/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CustomResourceDefinitionServiceName is the fully-qualified name of the
	// CustomResourceDefinitionService service.
	CustomResourceDefinitionServiceName = "clavel.core.v1.CustomResourceDefinitionService"
	// CustomResourceServiceName is the fully-qualified name of the CustomResourceService service.
	CustomResourceServiceName = "clavel.core.v1.CustomResourceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CustomResourceDefinitionServiceShowProcedure is the fully-qualified name of the
	// CustomResourceDefinitionService's Show RPC.
	CustomResourceDefinitionServiceShowProcedure = "/clavel.core.v1.CustomResourceDefinitionService/Show"
	// CustomResourceDefinitionServiceListProcedure is the fully-qualified name of the
	// CustomResourceDefinitionService's List RPC.
	CustomResourceDefinitionServiceListProcedure = "/clavel.core.v1.CustomResourceDefinitionService/List"
	// CustomResourceDefinitionServiceCreateProcedure is the fully-qualified name of the
	// CustomResourceDefinitionService's Create RPC.
	CustomResourceDefinitionServiceCreateProcedure = "/clavel.core.v1.CustomResourceDefinitionService/Create"
	// CustomResourceDefinitionServiceDeleteProcedure is the fully-qualified name of the
	// CustomResourceDefinitionService's Delete RPC.
	CustomResourceDefinitionServiceDeleteProcedure = "/clavel.core.v1.CustomResourceDefinitionService/Delete"
	// CustomResourceDefinitionServiceWatchProcedure is the fully-qualified name of the
	// CustomResourceDefinitionService's Watch RPC.
	CustomResourceDefinitionServiceWatchProcedure = "/clavel.core.v1.CustomResourceDefinitionService/Watch"
	// CustomResourceServiceShowProcedure is the fully-qualified name of the CustomResourceService's
	// Show RPC.
	CustomResourceServiceShowProcedure = "/clavel.core.v1.CustomResourceService/Show"
	// CustomResourceServiceListProcedure is the fully-qualified name of the CustomResourceService's
	// List RPC.
	CustomResourceServiceListProcedure = "/clavel.core.v1.CustomResourceService/List"
	// CustomResourceServiceCreateProcedure is the fully-qualified name of the CustomResourceService's
	// Create RPC.
	CustomResourceServiceCreateProcedure = "/clavel.core.v1.CustomResourceService/Create"
	// CustomResourceServiceUpdateProcedure is the fully-qualified name of the CustomResourceService's
	// Update RPC.
	CustomResourceServiceUpdateProcedure = "/clavel.core.v1.CustomResourceService/Update"
	// CustomResourceServiceDeleteProcedure is the fully-qualified name of the CustomResourceService's
	// Delete RPC.
	CustomResourceServiceDeleteProcedure = "/clavel.core.v1.CustomResourceService/Delete"
	// CustomResourceServiceWatchProcedure is the fully-qualified name of the CustomResourceService's
	// Watch RPC.
	CustomResourceServiceWatchProcedure = "/clavel.core.v1.CustomResourceService/Watch"
)

// CustomResourceDefinitionServiceClient is a client for the
// clavel.core.v1.CustomResourceDefinitionService service.
type CustomResourceDefinitionServiceClient interface {
	Show(context.Context, *connect.Request[v1.CustomResourceDefinitionServiceShowRequest]) (*connect.Response[v1.CustomResourceDefinitionServiceShowResponse], error)
	List(context.Context, *connect.Request[v1.CustomResourceDefinitionServiceListRequest]) (*connect.Response[v1.CustomResourceDefinitionServiceListResponse], error)
	Create(context.Context, *connect.Request[v1.CustomResourceDefinitionServiceCreateRequest]) (*connect.Response[v1.CustomResourceDefinitionServiceCreateResponse], error)
	Delete(context.Context, *connect.Request[v1.CustomResourceDefinitionServiceDeleteRequest]) (*connect.Response[v1.CustomResourceDefinitionServiceDeleteResponse], error)
	Watch(context.Context, *connect.Request[v1.CustomResourceDefinitionServiceWatchRequest]) (*connect.ServerStreamForClient[v1.CustomResourceDefinitionServiceWatchResponse], error)
}

// NewCustomResourceDefinitionServiceClient constructs a client for the
// clavel.core.v1.CustomResourceDefinitionService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCustomResourceDefinitionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CustomResourceDefinitionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	customResourceDefinitionServiceMethods := v1.File_clavel_core_v1_custom_resource_proto.Services().ByName("CustomResourceDefinitionService").Methods()
	return &customResourceDefinitionServiceClient{
		show: connect.NewClient[v1.CustomResourceDefinitionServiceShowRequest, v1.CustomResourceDefinitionServiceShowResponse](
			httpClient,
			baseURL+CustomResourceDefinitionServiceShowProcedure,
			connect.WithSchema(customResourceDefinitionServiceMethods.ByName("Show")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.CustomResourceDefinitionServiceListRequest, v1.CustomResourceDefinitionServiceListResponse](
			httpClient,
			baseURL+CustomResourceDefinitionServiceListProcedure,
			connect.WithSchema(customResourceDefinitionServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		create: connect.NewClient[v1.CustomResourceDefinitionServiceCreateRequest, v1.CustomResourceDefinitionServiceCreateResponse](
			httpClient,
			baseURL+CustomResourceDefinitionServiceCreateProcedure,
			connect.WithSchema(customResourceDefinitionServiceMethods.ByName("Create")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1.CustomResourceDefinitionServiceDeleteRequest, v1.CustomResourceDefinitionServiceDeleteResponse](
			httpClient,
			baseURL+CustomResourceDefinitionServiceDeleteProcedure,
			connect.WithSchema(customResourceDefinitionServiceMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		watch: connect.NewClient[v1.CustomResourceDefinitionServiceWatchRequest, v1.CustomResourceDefinitionServiceWatchResponse](
			httpClient,
			baseURL+CustomResourceDefinitionServiceWatchProcedure,
			connect.WithSchema(customResourceDefinitionServiceMethods.ByName("Watch")),
			connect.WithClientOptions(opts...),
		),
	}
}

// customResourceDefinitionServiceClient implements CustomResourceDefinitionServiceClient.
type customResourceDefinitionServiceClient struct {
	show   *connect.Client[v1.CustomResourceDefinitionServiceShowRequest, v1.CustomResourceDefinitionServiceShowResponse]
	list   *connect.Client[v1.CustomResourceDefinitionServiceListRequest, v1.CustomResourceDefinitionServiceListResponse]
	create *connect.Client[v1.CustomResourceDefinitionServiceCreateRequest, v1.CustomResourceDefinitionServiceCreateResponse]
	delete *connect.Client[v1.CustomResourceDefinitionServiceDeleteRequest, v1.CustomResourceDefinitionServiceDeleteResponse]
	watch  *connect.Client[v1.CustomResourceDefinitionServiceWatchRequest, v1.CustomResourceDefinitionServiceWatchResponse]
}

// Show calls clavel.core.v1.CustomResourceDefinitionService.Show.
func (c *customResourceDefinitionServiceClient) Show(ctx context.Context, req *connect.Request[v1.CustomResourceDefinitionServiceShowRequest]) (*connect.Response[v1.CustomResourceDefinitionServiceShowResponse], error) {
	return c.show.CallUnary(ctx, req)
}

// List calls clavel.core.v1.CustomResourceDefinitionService.List.
func (c *customResourceDefinitionServiceClient) List(ctx context.Context, req *connect.Request[v1.CustomResourceDefinitionServiceListRequest]) (*connect.Response[v1.CustomResourceDefinitionServiceListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Create calls clavel.core.v1.CustomResourceDefinitionService.Create.
func (c *customResourceDefinitionServiceClient) Create(ctx context.Context, req *connect.Request[v1.CustomResourceDefinitionServiceCreateRequest]) (*connect.Response[v1.CustomResourceDefinitionServiceCreateResponse], error) {
	return c.create.CallUnary(ctx, req)
}

// Delete calls clavel.core.v1.CustomResourceDefinitionService.Delete.
func (c *customResourceDefinitionServiceClient) Delete(ctx context.Context, req *connect.Request[v1.CustomResourceDefinitionServiceDeleteRequest]) (*connect.Response[v1.CustomResourceDefinitionServiceDeleteResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// Watch calls clavel.core.v1.CustomResourceDefinitionService.Watch.
func (c *customResourceDefinitionServiceClient) Watch(ctx context.Context, req *connect.Request[v1.CustomResourceDefinitionServiceWatchRequest]) (*connect.ServerStreamForClient[v1.CustomResourceDefinitionServiceWatchResponse], error) {
	return c.watch.CallServerStream(ctx, req)
}

// CustomResourceDefinitionServiceHandler is an implementation of the
// clavel.core.v1.CustomResourceDefinitionService service.
type CustomResourceDefinitionServiceHandler interface {
	Show(context.Context, *connect.Request[v1.CustomResourceDefinitionServiceShowRequest]) (*connect.Response[v1.CustomResourceDefinitionServiceShowResponse], error)
	List(context.Context, *connect.Request[v1.CustomResourceDefinitionServiceListRequest]) (*connect.Response[v1.CustomResourceDefinitionServiceListResponse], error)
	Create(context.Context, *connect.Request[v1.CustomResourceDefinitionServiceCreateRequest]) (*connect.Response[v1.CustomResourceDefinitionServiceCreateResponse], error)
	Delete(context.Context, *connect.Request[v1.CustomResourceDefinitionServiceDeleteRequest]) (*connect.Response[v1.CustomResourceDefinitionServiceDeleteResponse], error)
	Watch(context.Context, *connect.Request[v1.CustomResourceDefinitionServiceWatchRequest], *connect.ServerStream[v1.CustomResourceDefinitionServiceWatchResponse]) error
}

// NewCustomResourceDefinitionServiceHandler builds an HTTP handler from the service implementation.
// It returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCustomResourceDefinitionServiceHandler(svc CustomResourceDefinitionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	customResourceDefinitionServiceMethods := v1.File_clavel_core_v1_custom_resource_proto.Services().ByName("CustomResourceDefinitionService").Methods()
	customResourceDefinitionServiceShowHandler := connect.NewUnaryHandler(
		CustomResourceDefinitionServiceShowProcedure,
		svc.Show,
		connect.WithSchema(customResourceDefinitionServiceMethods.ByName("Show")),
		connect.WithHandlerOptions(opts...),
	)
	customResourceDefinitionServiceListHandler := connect.NewUnaryHandler(
		CustomResourceDefinitionServiceListProcedure,
		svc.List,
		connect.WithSchema(customResourceDefinitionServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	customResourceDefinitionServiceCreateHandler := connect.NewUnaryHandler(
		CustomResourceDefinitionServiceCreateProcedure,
		svc.Create,
		connect.WithSchema(customResourceDefinitionServiceMethods.ByName("Create")),
		connect.WithHandlerOptions(opts...),
	)
	customResourceDefinitionServiceDeleteHandler := connect.NewUnaryHandler(
		CustomResourceDefinitionServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(customResourceDefinitionServiceMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	customResourceDefinitionServiceWatchHandler := connect.NewServerStreamHandler(
		CustomResourceDefinitionServiceWatchProcedure,
		svc.Watch,
		connect.WithSchema(customResourceDefinitionServiceMethods.ByName("Watch")),
		connect.WithHandlerOptions(opts...),
	)
	return "/clavel.core.v1.CustomResourceDefinitionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CustomResourceDefinitionServiceShowProcedure:
			customResourceDefinitionServiceShowHandler.ServeHTTP(w, r)
		case CustomResourceDefinitionServiceListProcedure:
			customResourceDefinitionServiceListHandler.ServeHTTP(w, r)
		case CustomResourceDefinitionServiceCreateProcedure:
			customResourceDefinitionServiceCreateHandler.ServeHTTP(w, r)
		case CustomResourceDefinitionServiceDeleteProcedure:
			customResourceDefinitionServiceDeleteHandler.ServeHTTP(w, r)
		case CustomResourceDefinitionServiceWatchProcedure:
			customResourceDefinitionServiceWatchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCustomResourceDefinitionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCustomResourceDefinitionServiceHandler struct{}

func (UnimplementedCustomResourceDefinitionServiceHandler) Show(context.Context, *connect.Request[v1.CustomResourceDefinitionServiceShowRequest]) (*connect.Response[v1.CustomResourceDefinitionServiceShowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clavel.core.v1.CustomResourceDefinitionService.Show is not implemented"))
}

func (UnimplementedCustomResourceDefinitionServiceHandler) List(context.Context, *connect.Request[v1.CustomResourceDefinitionServiceListRequest]) (*connect.Response[v1.CustomResourceDefinitionServiceListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clavel.core.v1.CustomResourceDefinitionService.List is not implemented"))
}

func (UnimplementedCustomResourceDefinitionServiceHandler) Create(context.Context, *connect.Request[v1.CustomResourceDefinitionServiceCreateRequest]) (*connect.Response[v1.CustomResourceDefinitionServiceCreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clavel.core.v1.CustomResourceDefinitionService.Create is not implemented"))
}

func (UnimplementedCustomResourceDefinitionServiceHandler) Delete(context.Context, *connect.Request[v1.CustomResourceDefinitionServiceDeleteRequest]) (*connect.Response[v1.CustomResourceDefinitionServiceDeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clavel.core.v1.CustomResourceDefinitionService.Delete is not implemented"))
}

func (UnimplementedCustomResourceDefinitionServiceHandler) Watch(context.Context, *connect.Request[v1.CustomResourceDefinitionServiceWatchRequest], *connect.ServerStream[v1.CustomResourceDefinitionServiceWatchResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("clavel.core.v1.CustomResourceDefinitionService.Watch is not implemented"))
}

// CustomResourceServiceClient is a client for the clavel.core.v1.CustomResourceService service.
type CustomResourceServiceClient interface {
	Show(context.Context, *connect.Request[v1.CustomResourceServiceShowRequest]) (*connect.Response[v1.CustomResourceServiceShowResponse], error)
	List(context.Context, *connect.Request[v1.CustomResourceServiceListRequest]) (*connect.Response[v1.CustomResourceServiceListResponse], error)
	Create(context.Context, *connect.Request[v1.CustomResourceServiceCreateRequest]) (*connect.Response[v1.CustomResourceServiceCreateResponse], error)
	Update(context.Context, *connect.Request[v1.CustomResourceServiceUpdateRequest]) (*connect.Response[v1.CustomResourceServiceUpdateResponse], error)
	Delete(context.Context, *connect.Request[v1.CustomResourceServiceDeleteRequest]) (*connect.Response[v1.CustomResourceServiceDeleteResponse], error)
	Watch(context.Context, *connect.Request[v1.CustomResourceServiceWatchRequest]) (*connect.ServerStreamForClient[v1.CustomResourceServiceWatchResponse], error)
}

// NewCustomResourceServiceClient constructs a client for the clavel.core.v1.CustomResourceService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCustomResourceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CustomResourceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	customResourceServiceMethods := v1.File_clavel_core_v1_custom_resource_proto.Services().ByName("CustomResourceService").Methods()
	return &customResourceServiceClient{
		show: connect.NewClient[v1.CustomResourceServiceShowRequest, v1.CustomResourceServiceShowResponse](
			httpClient,
			baseURL+CustomResourceServiceShowProcedure,
			connect.WithSchema(customResourceServiceMethods.ByName("Show")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.CustomResourceServiceListRequest, v1.CustomResourceServiceListResponse](
			httpClient,
			baseURL+CustomResourceServiceListProcedure,
			connect.WithSchema(customResourceServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		create: connect.NewClient[v1.CustomResourceServiceCreateRequest, v1.CustomResourceServiceCreateResponse](
			httpClient,
			baseURL+CustomResourceServiceCreateProcedure,
			connect.WithSchema(customResourceServiceMethods.ByName("Create")),
			connect.WithClientOptions(opts...),
		),
		update: connect.NewClient[v1.CustomResourceServiceUpdateRequest, v1.CustomResourceServiceUpdateResponse](
			httpClient,
			baseURL+CustomResourceServiceUpdateProcedure,
			connect.WithSchema(customResourceServiceMethods.ByName("Update")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1.CustomResourceServiceDeleteRequest, v1.CustomResourceServiceDeleteResponse](
			httpClient,
			baseURL+CustomResourceServiceDeleteProcedure,
			connect.WithSchema(customResourceServiceMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		watch: connect.NewClient[v1.CustomResourceServiceWatchRequest, v1.CustomResourceServiceWatchResponse](
			httpClient,
			baseURL+CustomResourceServiceWatchProcedure,
			connect.WithSchema(customResourceServiceMethods.ByName("Watch")),
			connect.WithClientOptions(opts...),
		),
	}
}

// customResourceServiceClient implements CustomResourceServiceClient.
type customResourceServiceClient struct {
	show   *connect.Client[v1.CustomResourceServiceShowRequest, v1.CustomResourceServiceShowResponse]
	list   *connect.Client[v1.CustomResourceServiceListRequest, v1.CustomResourceServiceListResponse]
	create *connect.Client[v1.CustomResourceServiceCreateRequest, v1.CustomResourceServiceCreateResponse]
	update *connect.Client[v1.CustomResourceServiceUpdateRequest, v1.CustomResourceServiceUpdateResponse]
	delete *connect.Client[v1.CustomResourceServiceDeleteRequest, v1.CustomResourceServiceDeleteResponse]
	watch  *connect.Client[v1.CustomResourceServiceWatchRequest, v1.CustomResourceServiceWatchResponse]
}

// Show calls clavel.core.v1.CustomResourceService.Show.
func (c *customResourceServiceClient) Show(ctx context.Context, req *connect.Request[v1.CustomResourceServiceShowRequest]) (*connect.Response[v1.CustomResourceServiceShowResponse], error) {
	return c.show.CallUnary(ctx, req)
}

// List calls clavel.core.v1.CustomResourceService.List.
func (c *customResourceServiceClient) List(ctx context.Context, req *connect.Request[v1.CustomResourceServiceListRequest]) (*connect.Response[v1.CustomResourceServiceListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Create calls clavel.core.v1.CustomResourceService.Create.
func (c *customResourceServiceClient) Create(ctx context.Context, req *connect.Request[v1.CustomResourceServiceCreateRequest]) (*connect.Response[v1.CustomResourceServiceCreateResponse], error) {
	return c.create.CallUnary(ctx, req)
}

// Update calls clavel.core.v1.CustomResourceService.Update.
func (c *customResourceServiceClient) Update(ctx context.Context, req *connect.Request[v1.CustomResourceServiceUpdateRequest]) (*connect.Response[v1.CustomResourceServiceUpdateResponse], error) {
	return c.update.CallUnary(ctx, req)
}

// Delete calls clavel.core.v1.CustomResourceService.Delete.
func (c *customResourceServiceClient) Delete(ctx context.Context, req *connect.Request[v1.CustomResourceServiceDeleteRequest]) (*connect.Response[v1.CustomResourceServiceDeleteResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// Watch calls clavel.core.v1.CustomResourceService.Watch.
func (c *customResourceServiceClient) Watch(ctx context.Context, req *connect.Request[v1.CustomResourceServiceWatchRequest]) (*connect.ServerStreamForClient[v1.CustomResourceServiceWatchResponse], error) {
	return c.watch.CallServerStream(ctx, req)
}

// CustomResourceServiceHandler is an implementation of the clavel.core.v1.CustomResourceService
// service.
type CustomResourceServiceHandler interface {
	Show(context.Context, *connect.Request[v1.CustomResourceServiceShowRequest]) (*connect.Response[v1.CustomResourceServiceShowResponse], error)
	List(context.Context, *connect.Request[v1.CustomResourceServiceListRequest]) (*connect.Response[v1.CustomResourceServiceListResponse], error)
	Create(context.Context, *connect.Request[v1.CustomResourceServiceCreateRequest]) (*connect.Response[v1.CustomResourceServiceCreateResponse], error)
	Update(context.Context, *connect.Request[v1.CustomResourceServiceUpdateRequest]) (*connect.Response[v1.CustomResourceServiceUpdateResponse], error)
	Delete(context.Context, *connect.Request[v1.CustomResourceServiceDeleteRequest]) (*connect.Response[v1.CustomResourceServiceDeleteResponse], error)
	Watch(context.Context, *connect.Request[v1.CustomResourceServiceWatchRequest], *connect.ServerStream[v1.CustomResourceServiceWatchResponse]) error
}

// NewCustomResourceServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCustomResourceServiceHandler(svc CustomResourceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	customResourceServiceMethods := v1.File_clavel_core_v1_custom_resource_proto.Services().ByName("CustomResourceService").Methods()
	customResourceServiceShowHandler := connect.NewUnaryHandler(
		CustomResourceServiceShowProcedure,
		svc.Show,
		connect.WithSchema(customResourceServiceMethods.ByName("Show")),
		connect.WithHandlerOptions(opts...),
	)
	customResourceServiceListHandler := connect.NewUnaryHandler(
		CustomResourceServiceListProcedure,
		svc.List,
		connect.WithSchema(customResourceServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	customResourceServiceCreateHandler := connect.NewUnaryHandler(
		CustomResourceServiceCreateProcedure,
		svc.Create,
		connect.WithSchema(customResourceServiceMethods.ByName("Create")),
		connect.WithHandlerOptions(opts...),
	)
	customResourceServiceUpdateHandler := connect.NewUnaryHandler(
		CustomResourceServiceUpdateProcedure,
		svc.Update,
		connect.WithSchema(customResourceServiceMethods.ByName("Update")),
		connect.WithHandlerOptions(opts...),
	)
	customResourceServiceDeleteHandler := connect.NewUnaryHandler(
		CustomResourceServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(customResourceServiceMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	customResourceServiceWatchHandler := connect.NewServerStreamHandler(
		CustomResourceServiceWatchProcedure,
		svc.Watch,
		connect.WithSchema(customResourceServiceMethods.ByName("Watch")),
		connect.WithHandlerOptions(opts...),
	)
	return "/clavel.core.v1.CustomResourceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CustomResourceServiceShowProcedure:
			customResourceServiceShowHandler.ServeHTTP(w, r)
		case CustomResourceServiceListProcedure:
			customResourceServiceListHandler.ServeHTTP(w, r)
		case CustomResourceServiceCreateProcedure:
			customResourceServiceCreateHandler.ServeHTTP(w, r)
		case CustomResourceServiceUpdateProcedure:
			customResourceServiceUpdateHandler.ServeHTTP(w, r)
		case CustomResourceServiceDeleteProcedure:
			customResourceServiceDeleteHandler.ServeHTTP(w, r)
		case CustomResourceServiceWatchProcedure:
			customResourceServiceWatchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCustomResourceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCustomResourceServiceHandler struct{}

func (UnimplementedCustomResourceServiceHandler) Show(context.Context, *connect.Request[v1.CustomResourceServiceShowRequest]) (*connect.Response[v1.CustomResourceServiceShowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clavel.core.v1.CustomResourceService.Show is not implemented"))
}

func (UnimplementedCustomResourceServiceHandler) List(context.Context, *connect.Request[v1.CustomResourceServiceListRequest]) (*connect.Response[v1.CustomResourceServiceListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clavel.core.v1.CustomResourceService.List is not implemented"))
}

func (UnimplementedCustomResourceServiceHandler) Create(context.Context, *connect.Request[v1.CustomResourceServiceCreateRequest]) (*connect.Response[v1.CustomResourceServiceCreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clavel.core.v1.CustomResourceService.Create is not implemented"))
}

func (UnimplementedCustomResourceServiceHandler) Update(context.Context, *connect.Request[v1.CustomResourceServiceUpdateRequest]) (*connect.Response[v1.CustomResourceServiceUpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clavel.core.v1.CustomResourceService.Update is not implemented"))
}

func (UnimplementedCustomResourceServiceHandler) Delete(context.Context, *connect.Request[v1.CustomResourceServiceDeleteRequest]) (*connect.Response[v1.CustomResourceServiceDeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clavel.core.v1.CustomResourceService.Delete is not implemented"))
}

func (UnimplementedCustomResourceServiceHandler) Watch(context.Context, *connect.Request[v1.CustomResourceServiceWatchRequest], *connect.ServerStream[v1.CustomResourceServiceWatchResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("clavel.core.v1.CustomResourceService.Watch is not implemented"))
}
