// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: clavel/source/v1/source.proto

package sourcev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/erikeah/clavel/pkg/api/source/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SourceServiceName is the fully-qualified name of the SourceService service.
	SourceServiceName = "clavel.source.v1.SourceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SourceServiceShowProcedure is the fully-qualified name of the SourceService's Show RPC.
	SourceServiceShowProcedure = "/clavel.source.v1.SourceService/Show"
	// SourceServiceListProcedure is the fully-qualified name of the SourceService's List RPC.
	SourceServiceListProcedure = "/clavel.source.v1.SourceService/List"
	// SourceServiceCreateProcedure is the fully-qualified name of the SourceService's Create RPC.
	SourceServiceCreateProcedure = "/clavel.source.v1.SourceService/Create"
	// SourceServiceUpdateProcedure is the fully-qualified name of the SourceService's Update RPC.
	SourceServiceUpdateProcedure = "/clavel.source.v1.SourceService/Update"
	// SourceServiceDeleteProcedure is the fully-qualified name of the SourceService's Delete RPC.
	SourceServiceDeleteProcedure = "/clavel.source.v1.SourceService/Delete"
	// SourceServiceWatchProcedure is the fully-qualified name of the SourceService's Watch RPC.
	SourceServiceWatchProcedure = "/clavel.source.v1.SourceService/Watch"
)

// SourceServiceClient is a client for the clavel.source.v1.SourceService service.
type SourceServiceClient interface {
	Show(context.Context, *connect.Request[v1.SourceServiceShowRequest]) (*connect.Response[v1.SourceServiceShowResponse], error)
	List(context.Context, *connect.Request[v1.SourceServiceListRequest]) (*connect.Response[v1.SourceServiceListResponse], error)
	Create(context.Context, *connect.Request[v1.SourceServiceCreateRequest]) (*connect.Response[v1.SourceServiceCreateResponse], error)
	Update(context.Context, *connect.Request[v1.SourceServiceUpdateRequest]) (*connect.Response[v1.SourceServiceUpdateResponse], error)
	Delete(context.Context, *connect.Request[v1.SourceServiceDeleteRequest]) (*connect.Response[v1.SourceServiceDeleteResponse], error)
	Watch(context.Context, *connect.Request[v1.SourceServiceWatchRequest]) (*connect.ServerStreamForClient[v1.SourceServiceWatchResponse], error)
}

// NewSourceServiceClient constructs a client for the clavel.source.v1.SourceService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSourceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SourceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sourceServiceMethods := v1.File_clavel_source_v1_source_proto.Services().ByName("SourceService").Methods()
	return &sourceServiceClient{
		show: connect.NewClient[v1.SourceServiceShowRequest, v1.SourceServiceShowResponse](
			httpClient,
			baseURL+SourceServiceShowProcedure,
			connect.WithSchema(sourceServiceMethods.ByName("Show")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.SourceServiceListRequest, v1.SourceServiceListResponse](
			httpClient,
			baseURL+SourceServiceListProcedure,
			connect.WithSchema(sourceServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		create: connect.NewClient[v1.SourceServiceCreateRequest, v1.SourceServiceCreateResponse](
			httpClient,
			baseURL+SourceServiceCreateProcedure,
			connect.WithSchema(sourceServiceMethods.ByName("Create")),
			connect.WithClientOptions(opts...),
		),
		update: connect.NewClient[v1.SourceServiceUpdateRequest, v1.SourceServiceUpdateResponse](
			httpClient,
			baseURL+SourceServiceUpdateProcedure,
			connect.WithSchema(sourceServiceMethods.ByName("Update")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1.SourceServiceDeleteRequest, v1.SourceServiceDeleteResponse](
			httpClient,
			baseURL+SourceServiceDeleteProcedure,
			connect.WithSchema(sourceServiceMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		watch: connect.NewClient[v1.SourceServiceWatchRequest, v1.SourceServiceWatchResponse](
			httpClient,
			baseURL+SourceServiceWatchProcedure,
			connect.WithSchema(sourceServiceMethods.ByName("Watch")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sourceServiceClient implements SourceServiceClient.
type sourceServiceClient struct {
	show   *connect.Client[v1.SourceServiceShowRequest, v1.SourceServiceShowResponse]
	list   *connect.Client[v1.SourceServiceListRequest, v1.SourceServiceListResponse]
	create *connect.Client[v1.SourceServiceCreateRequest, v1.SourceServiceCreateResponse]
	update *connect.Client[v1.SourceServiceUpdateRequest, v1.SourceServiceUpdateResponse]
	delete *connect.Client[v1.SourceServiceDeleteRequest, v1.SourceServiceDeleteResponse]
	watch  *connect.Client[v1.SourceServiceWatchRequest, v1.SourceServiceWatchResponse]
}

// Show calls clavel.source.v1.SourceService.Show.
func (c *sourceServiceClient) Show(ctx context.Context, req *connect.Request[v1.SourceServiceShowRequest]) (*connect.Response[v1.SourceServiceShowResponse], error) {
	return c.show.CallUnary(ctx, req)
}

// List calls clavel.source.v1.SourceService.List.
func (c *sourceServiceClient) List(ctx context.Context, req *connect.Request[v1.SourceServiceListRequest]) (*connect.Response[v1.SourceServiceListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Create calls clavel.source.v1.SourceService.Create.
func (c *sourceServiceClient) Create(ctx context.Context, req *connect.Request[v1.SourceServiceCreateRequest]) (*connect.Response[v1.SourceServiceCreateResponse], error) {
	return c.create.CallUnary(ctx, req)
}

// Update calls clavel.source.v1.SourceService.Update.
func (c *sourceServiceClient) Update(ctx context.Context, req *connect.Request[v1.SourceServiceUpdateRequest]) (*connect.Response[v1.SourceServiceUpdateResponse], error) {
	return c.update.CallUnary(ctx, req)
}

// Delete calls clavel.source.v1.SourceService.Delete.
func (c *sourceServiceClient) Delete(ctx context.Context, req *connect.Request[v1.SourceServiceDeleteRequest]) (*connect.Response[v1.SourceServiceDeleteResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// Watch calls clavel.source.v1.SourceService.Watch.
func (c *sourceServiceClient) Watch(ctx context.Context, req *connect.Request[v1.SourceServiceWatchRequest]) (*connect.ServerStreamForClient[v1.SourceServiceWatchResponse], error) {
	return c.watch.CallServerStream(ctx, req)
}

// SourceServiceHandler is an implementation of the clavel.source.v1.SourceService service.
type SourceServiceHandler interface {
	Show(context.Context, *connect.Request[v1.SourceServiceShowRequest]) (*connect.Response[v1.SourceServiceShowResponse], error)
	List(context.Context, *connect.Request[v1.SourceServiceListRequest]) (*connect.Response[v1.SourceServiceListResponse], error)
	Create(context.Context, *connect.Request[v1.SourceServiceCreateRequest]) (*connect.Response[v1.SourceServiceCreateResponse], error)
	Update(context.Context, *connect.Request[v1.SourceServiceUpdateRequest]) (*connect.Response[v1.SourceServiceUpdateResponse], error)
	Delete(context.Context, *connect.Request[v1.SourceServiceDeleteRequest]) (*connect.Response[v1.SourceServiceDeleteResponse], error)
	Watch(context.Context, *connect.Request[v1.SourceServiceWatchRequest], *connect.ServerStream[v1.SourceServiceWatchResponse]) error
}

// NewSourceServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSourceServiceHandler(svc SourceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sourceServiceMethods := v1.File_clavel_source_v1_source_proto.Services().ByName("SourceService").Methods()
	sourceServiceShowHandler := connect.NewUnaryHandler(
		SourceServiceShowProcedure,
		svc.Show,
		connect.WithSchema(sourceServiceMethods.ByName("Show")),
		connect.WithHandlerOptions(opts...),
	)
	sourceServiceListHandler := connect.NewUnaryHandler(
		SourceServiceListProcedure,
		svc.List,
		connect.WithSchema(sourceServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	sourceServiceCreateHandler := connect.NewUnaryHandler(
		SourceServiceCreateProcedure,
		svc.Create,
		connect.WithSchema(sourceServiceMethods.ByName("Create")),
		connect.WithHandlerOptions(opts...),
	)
	sourceServiceUpdateHandler := connect.NewUnaryHandler(
		SourceServiceUpdateProcedure,
		svc.Update,
		connect.WithSchema(sourceServiceMethods.ByName("Update")),
		connect.WithHandlerOptions(opts...),
	)
	sourceServiceDeleteHandler := connect.NewUnaryHandler(
		SourceServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(sourceServiceMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	sourceServiceWatchHandler := connect.NewServerStreamHandler(
		SourceServiceWatchProcedure,
		svc.Watch,
		connect.WithSchema(sourceServiceMethods.ByName("Watch")),
		connect.WithHandlerOptions(opts...),
	)
	return "/clavel.source.v1.SourceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SourceServiceShowProcedure:
			sourceServiceShowHandler.ServeHTTP(w, r)
		case SourceServiceListProcedure:
			sourceServiceListHandler.ServeHTTP(w, r)
		case SourceServiceCreateProcedure:
			sourceServiceCreateHandler.ServeHTTP(w, r)
		case SourceServiceUpdateProcedure:
			sourceServiceUpdateHandler.ServeHTTP(w, r)
		case SourceServiceDeleteProcedure:
			sourceServiceDeleteHandler.ServeHTTP(w, r)
		case SourceServiceWatchProcedure:
			sourceServiceWatchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSourceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSourceServiceHandler struct{}

func (UnimplementedSourceServiceHandler) Show(context.Context, *connect.Request[v1.SourceServiceShowRequest]) (*connect.Response[v1.SourceServiceShowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clavel.source.v1.SourceService.Show is not implemented"))
}

func (UnimplementedSourceServiceHandler) List(context.Context, *connect.Request[v1.SourceServiceListRequest]) (*connect.Response[v1.SourceServiceListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clavel.source.v1.SourceService.List is not implemented"))
}

func (UnimplementedSourceServiceHandler) Create(context.Context, *connect.Request[v1.SourceServiceCreateRequest]) (*connect.Response[v1.SourceServiceCreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clavel.source.v1.SourceService.Create is not implemented"))
}

func (UnimplementedSourceServiceHandler) Update(context.Context, *connect.Request[v1.SourceServiceUpdateRequest]) (*connect.Response[v1.SourceServiceUpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clavel.source.v1.SourceService.Update is not implemented"))
}

func (UnimplementedSourceServiceHandler) Delete(context.Context, *connect.Request[v1.SourceServiceDeleteRequest]) (*connect.Response[v1.SourceServiceDeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clavel.source.v1.SourceService.Delete is not implemented"))
}

func (UnimplementedSourceServiceHandler) Watch(context.Context, *connect.Request[v1.SourceServiceWatchRequest], *connect.ServerStream[v1.SourceServiceWatchResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("clavel.source.v1.SourceService.Watch is not implemented"))
}
